### ISSUE TITLE
Windows 2022 and Red Hat VirtIO Ethernet Adapter

### ISSUE THREAD

**Issue by Quembar** [virtio-win/kvm-guest-drivers-windows#998] opened 2023-11-16 10:19 UTC
**Describe the bug**
The installation of virtio-win-0.1.240 ends up without the installed NIC-Drv: 'Red Hat VirtIO Ethernet Adapter'
In Network setting I does not see a NIC

**To Reproduce**
Install a fresh Windows Server 2022 Standard Evalution ans install the libvirt-tools 0.1.240 afterwards.

**Expected behavior**
I expect a visible NIC to configure the LAN-Access

**Screenshots**
![231116_110348-001](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/58207372/658b46cc-49df-48e3-bb59-e040c4cc05fd)
![231116_110524-001](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/58207372/0f997ced-d1d9-40e5-a508-2c13e71b6ffc)

**Host:**
 - Disto: [openSUSE]
 - Kernel
 Linux jupiter 5.14.21-150400.24.97-default #1 SMP PREEMPT_DYNAMIC Fri Oct 27 10:29:06 UTC 2023 (8546fda) x86_64 x86_64 x86_64 GNU/Linux
 - QEMU version
 6.2.0
 - QEMU command line 
 - libvirt version
8.0.0
 - libvirt XML file

**VM:**
 - Windows version
 Windows Server 2022 Standard Evalution
 - Which driver has a problem
Red Hat VirtIO Ethernet Adapter 

**Additional context**
The same issue occurs if I use the RTL8139 NIC as device in the config of the VM
There are other VM (Windows Server 2019 Standard Evalution) in this hypervisor running w/o problems. Even if I update a Win 2019 Srv VM with the new virtio-tools 0.1.240 the NIC remain visible.

**Comment by sb-ntnx** [comment] 2023-11-16 10:33
Duplicate of https://github.com/virtio-win/kvm-guest-drivers-windows/issues/750, not specific to virtio-win drivers suite and affects only (so far) German localization.

**Closed** 2023-11-16 12:05 UTC
Labels: Bug

**Comment by zalnaRs** [comment] 2024-07-21 09:15
> Duplicate of #750, not specific to virtio-win drivers suite and affects only (so far) German localization.

and hungarian

**Comment by YanVugenfirer** [comment] 2024-07-21 09:21
@zalnaRs Thanks a lot for the update! We are currently discussing this issues with MS. While they are going to fix it in the upcoming Windows releases, we definitely need to know more in the impact in the currently released Windows versions in order to convince them to fix.
Can you please tell what Windows version(s) are affected?

**Comment by gilbertoferreira** [comment] 2026-05-21 02:01
Strangely enought, it's seem that windows 2022 still have problem with new virtio net drivers yet.
I have has tested with virtio-win-0.1.285-1 and get this issue with AD and FileServer.
Just changed to e1000 and works fine.
Using Proxmox VE 9.1.16
