### ISSUE TITLE
Poor performance with vioscsi and scsi-block (AHCI SSD)

### ISSUE THREAD

**Issue by tomty89** [virtio-win/kvm-guest-drivers-windows#63] opened 2016-04-30 14:21 UTC
For some reason there seems to be a weird bottleneck on its performance when vioscsi works with scsi-block (but not scsi-hd).

The passthrough'd storage is an Intel 530 240GB SATA SSD on Intel H87 AHCI (and obviously the passthrough'd SCSI layer is the SATL provided by libata-scsi). qemu 2.5.0 / linux 4.5.1 / Windows 10 Build 10586. Tested with both drivers in virtio-win-0.1.117.iso and virtio-win-0.1.102.iso

`qemu-system-x86_64 -enable-kvm -cpu host -smp cores=4 -m 4G -net bridge -net nic -full-screen -drive file=disks/win10__.qcow2,format=qcow2,cache=none,aio=native -drive file=/dev/sdb,format=raw,cache=none,aio=native,if=none,id=bench -device virtio-scsi-pci -device scsi-block,drive=bench`:

![vioscsi_2](https://cloud.githubusercontent.com/assets/8604057/14940652/00c8e782-0fb2-11e6-918a-02e74ebfba14.PNG)

`qemu-system-x86_64 -enable-kvm -cpu host -smp cores=4 -m 4G -net bridge -net nic -full-screen -drive file=disks/win10__.qcow2,format=qcow2,cache=none,aio=native -drive file=/dev/sdb,format=raw,cache=none,aio=native,if=none,id=bench -device virtio-scsi-pci -device scsi-hd,drive=bench`:

![vioscsi_hd_2](https://cloud.githubusercontent.com/assets/8604057/14940715/3ebf7612-0fb4-11e6-8554-47b9c47feaee.PNG)

`qemu-system-x86_64 -enable-kvm -cpu host -smp cores=4 -m 4G -net bridge -net nic -full-screen -drive file=disks/win10__.qcow2,format=qcow2,cache=none,aio=native -drive file=/dev/sdb,format=raw,cache=none,aio=native,if=virtio`:

![viostor](https://cloud.githubusercontent.com/assets/8604057/14936471/17a9e3ee-0f20-11e6-80cb-308c5e9b0505.PNG)

`qemu-system-x86_64 -enable-kvm -cpu host -smp cores=4 -m 4G -net bridge -net nic -full-screen -drive file=disks/win10__.qcow2,format=qcow2,cache=none,aio=native -drive file=/dev/sdb,format=raw,cache=none,aio=native,if=none,id=bench -device virtio-blk-pci,drive=bench,scsi=on`:

![viostor_scsi](https://cloud.githubusercontent.com/assets/8604057/14936478/3c28f250-0f20-11e6-8ebb-cfe94b454226.PNG)

(Note: I wanted to see if enabling SCSI passthrough on `virtio-blk-pci` would trigger the same issue. However, `scsi=on` seems to be a no-op when the guest is Windows, since `viostor` does not work the same way as `virtio-blk` in Linux. Is it a bug or for some reason intended btw?)

**Comment by tomty89** [comment] 2016-04-30 14:24
As a reference, I also ran the benchmark with the NVMe emulation in qemu. Works pretty well btw.

`qemu-system-x86_64 -enable-kvm -cpu host -smp cores=4 -m 4G -net bridge -net nic -full-screen -drive file=disks/win10__.qcow2,format=qcow2,cache=none,aio=native -drive file=/dev/sdb,format=raw,cache=none,aio=native,if=none,id=bench -device nvme,drive=bench,serial=intel530`:

![nvme](https://cloud.githubusercontent.com/assets/8604057/14936551/396945cc-0f22-11e6-8038-44b8a2693747.PNG)

**Comment by tomty89** [comment] 2016-05-02 10:58
Okay figured it out. Turns out to be caused by [a bug in libata](https://bugzilla.kernel.org/show_bug.cgi?id=105931). Since scsi-block does SCSI passthrough, CmdQue=0 set by libata is exposed to Windows, which apparently prevents command queuing.

CmdQue=0:
![cmdque_0](https://cloud.githubusercontent.com/assets/8604057/14952877/07a8891e-1097-11e6-80a4-818eaee6900d.PNG)

CmdQue=1:
![cmdque_1](https://cloud.githubusercontent.com/assets/8604057/14952880/0e7deffe-1097-11e6-8efa-c4590ba2e3f9.PNG)

It can be fixed with a patch to the kernel like this:
```
diff --git a/drivers/ata/libata-scsi.c~ b/drivers/ata/libata-scsi.c
index e417e1a..212aa3d 100644
--- a/drivers/ata/libata-scsi.c~
+++ b/drivers/ata/libata-scsi.c
@@ -2007,7 +2007,10 @@ static unsigned int ata_scsiop_inq_std(struct ata_scsi_args *args, u8 *rbuf)
                0,
                0x5,    /* claim SPC-3 version compatibility */
                2,
-               95 - 4
+               95 - 4,
+               0,
+               0,
+               2
        };
 
        VPRINTK("ENTER\n");
```

Ideally I suppose the bit should be toggled according to whether NCQ is enabled though. I will try to come up with a patch doing that and send it to the linux-ide mailing list.

I think it's better to leave this report open until a fix gets into upstream kernel, but sure it's you guys' call.

**Comment by YanVugenfirer** [comment] 2016-05-02 11:01
Thank you for digging into the issue and finding the cause.

I will keep the issue open for now as a reference for others.

**Comment by tomty89** [comment] 2016-05-03 09:38
> Ideally I suppose the bit should be toggled according to whether NCQ is enabled though.

Actually I might be wrong about that. Perhaps the CmdQue bit should be set to 1 statically:

![0](https://cloud.githubusercontent.com/assets/8604057/14979568/c104b7a2-1155-11e6-8656-21a71c45aa31.png)

![1](https://cloud.githubusercontent.com/assets/8604057/14979576/ce170a08-1155-11e6-984c-c5d62f4f5c12.png)

**Comment by YanVugenfirer** [comment] 2017-02-15 13:57
Fixed in Linux kernel: http://lxr.free-electrons.com/source/drivers/ata/libata-scsi.c#L2099

**Closed by YanVugenfirer** 2017-02-15 13:57 UTC
