### ISSUE TITLE
BSOD Balloon driver crashing Windows 7 64bit SP1 (fully updated).

### ISSUE THREAD

**Issue by Neopallium** [virtio-win/kvm-guest-drivers-windows#61] opened 2016-04-23 17:04 UTC
I have tried to install 4 different versions:
0.1.102, 0.1.112, 0.1.113, 0.1.117

They all crash during install of the driver.  I have to reboot in Safe Mode to uninstall the driver.

Also I noticed something odd about the virtio-win-0.1*.iso most are about 54Mbyte but version 0.1.102 is about 100Mbytes larger (153Mbyte).

When I mount the 54Mbyte isos on linux and use "du -sh /media/cdrom" it return 217Mbytes for the contents, but "df -h /media/cdrom" returns 55Mbytes.  I don't understand how there could be 217Mbytes on the iso.  They don't seem to be compressed.

I can still copy all the files off and get about the same amount of data.  I am not sure if the iso have been truncated or if some of the files are damaged.

**Comment by vrozenfe** [comment] 2016-04-24 09:32
Can you please specify the BSOD error code as well as qemu and kvm versions?

Thanks,
Vadim.

**Comment by kmyid** [comment] 2016-07-15 22:50
I second on this. 

QEMU emulator version 2.6.0 (qemu-2.6.0-4.fc24)
Kernel 4.6.4 (4.6.4-301.fc24.x86_64)

BSOD error screen
![screenshot from 2016-07-16 00-48-04](https://cloud.githubusercontent.com/assets/7147797/16890462/36109cdc-4aef-11e6-84b0-64a060b13811.png)

**Comment by vrozenfe** [comment] 2016-07-16 03:06
According to bugcheck parameters it looks like you are trying to install a wrong driver (something like Win8 driver on Win7 platform). Can you please provide the VM platform's version and virtio-win drivers installation path.

Cheers,
Vadim.

**Comment by kmyid** [comment] 2016-07-16 09:32
Hello,

I installed the drivers in the iso, under the sub directories for windows 7 amd64. 
The package I used to get the iso is virtio-win-0.1.102 from repo virtio-win-stable in fedora.

Thanks,
Kwang

**Comment by vrozenfe** [comment] 2016-07-17 04:24
Can you share the relevant dump file for analysis?

Thanks,
Vadim.

**Comment by kmyid** [comment] 2016-07-17 12:51
Hello, 

I must admit that I am not really familiar with this kind of stuff.
Can you point me to which file that I should share with you?

Thanks,
kwang

**Comment by vrozenfe** [comment] 2016-07-17 13:12
The Kernel Memory Dump file by default should be written to %SystemRoot%\Memory.dmp .

Best regards,
Vadim.

**Comment by kmyid** [comment] 2016-07-20 06:49
Hello, 

I installed on a fresh machine and now it works.
I however found that there are duplicate dll in the current stable package, for the serial driver and the balloon driver. I think this maybe the cause, as now the serial driver causes BSOD.

Thanks,
Kwang

**Comment by YanVugenfirer** [comment] 2016-07-20 10:58
Hi,

The duplicate DLLSs shouldn't be a problem. They are WDF coinstallers that
should be present in both drivers. During installation if WDF is not
present in OS - it will be installed.

Please send us memory dump so we could investigate the root cause.

Best regards,
Yan.

**Comment by kmyid** [comment] 2016-07-20 15:02
Okay, I uploaded the dump to dropbox :-) 
Just let me know once you get it, since I don't want it to be up there forever.

https://www.dropbox.com/s/jns4y7sez23ko26/MEMORY.DMP?dl=0

One interesting thing is that all the drivers install well if you install them from what you can get at

http://www.spice-space.org/download.html

I am currently using the version from there. It seems like it's the one shipped in the fedora repo that's the problem.

**Comment by Neopallium** [comment] 2016-07-20 15:59
I was also using the drivers from the fedora repo:

https://fedoraproject.org/wiki/Windows_Virtio_Drivers

When I have some time I will try the spice installer.  Does it have the Balloon driver?  That is the main driver that I want to use.

**Comment by kmyid** [comment] 2016-07-20 16:30
@Neopallium Indeed they do. They seem to have all the drivers there.

**Comment by vrozenfe** [comment] 2016-07-21 00:31
I went very briefly through https://www.dropbox.com/s/jns4y7sez23ko26/MEMORY.DMP?dl=0
your target system is Win7-64
0: kd> !targetinfo
Windows 7 Built by: 7601.23392.amd64fre.win7sp1_ldr.160317-0600, Service Pack 1

but balloon driver is win8-64
0: kd> !lmi balloon
Loaded Module Info: [balloon] 
         Module: balloon
   Base Address: fffff8800e5de000
     Image Name: balloon.sys
   Machine Type: 34404 (X64)
     Time Stamp: 54ff4382 Wed Mar 11 06:18:26 2015
           Size: d000
       CheckSum: 1632e
Characteristics: 22  
Debug Data Dirs: Type  Size     VA  Pointer
             CODEVIEW    88,  5264,    4064 RSDS - GUID: {71AD10E0-B4A5-428D-A9C1-588076FA4021}
               Age: 1, Pdb: C:\cygwin64\tmp\build\source\internal-kvm-guest-drivers-windows\Balloon\sys\objfre_win8_amd64\amd64\balloon.pdb

Cheers,
Vadim.

**Comment by kmyid** [comment] 2016-07-21 04:22
That's quite weird since I believe I installed the win7 driver by explicitly selecting it.
I guess, there's some issue with the Fedora package?

**Comment by vrozenfe** [comment] 2016-07-21 10:56
balloon driver from virtio-win-0.1.102/Balloon/w7/amd64 (https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso) has different timestamp:
        Time Type        Size      RVA  Pointer
    -------- ------- -------- -------- --------
    54FF4358 cv            88 000051B8     3BB8    Format: RSDS, {62595B76-2ACB-431E-BEFA-A11FC8F003F5}, 1, c:\cygwin64\tmp\build\source\internal-kvm-guest-drivers-windows\balloon\sys\objfre_wnet_amd64\amd64\balloon.pdb

while w8 is as follow:
        Time Type        Size      RVA  Pointer
    -------- ------- -------- -------- --------
    54FF4382 cv            88 00005264     4064    Format: RSDS, {71AD10E0-B4A5-428D-A9C1-588076FA4021}, 1, C:\cygwin64\tmp\build\source\internal-kvm-guest-drivers-windows\Balloon\sys\objfre_win8_amd64\amd64\balloon.pdb

time-stamp 54FF4382 is the same as on BSOD screen-shot
https://cloud.githubusercontent.com/assets/7147797/16890462/36109cdc-4aef-11e6-84b0-64a060b13811.png

**Comment by kmyid** [comment] 2016-07-21 14:05
I see...  I remember that when installing, at one point there was a case when I just simply designated the whole iso image as source for the driver. While being careful to select the win7 in the first driver, I was lazy and selected the iso after some others. So my bad...

**Comment by Neopallium** [comment] 2016-08-06 11:59
I finally got the Balloon driver working from:
http://www.spice-space.org/download.html

I had to manually remove the previous balloon.sys driver (mount image on linux to delete the file).

Is it normal for windows to report high memory usage when using the Balloon driver?
Host memory usage of the qemu process is lower.

![high_memory_usage_balloon](https://cloud.githubusercontent.com/assets/68307/17456587/88343d76-5c0f-11e6-90cc-37fac83cc2fe.png)

When "current allocation" and "maximum allocation" are set to the same value, windows reports the correct usage:

![memory_usage_no_balloon](https://cloud.githubusercontent.com/assets/68307/17456588/8d3c7752-5c0f-11e6-99a2-e1d5a8ae8905.png)

**Comment by YanVugenfirer** [comment] 2016-08-06 13:01
Hi,

If you inflate the ballon than definitely you should see high memory usage. After all it will allocate guest physical memory.

Best regards,
Yan.

**Comment by Neopallium** [comment] 2016-08-06 13:51
Ah.  I thought the "Current allocation" setting was just how much to give the VM when it starts.  I was thinking of it as more of a minimum.  I had assumed the ballooning would be based on available memory on the host.

Increasing the "Current allocation" decreased the balloon size in the VM.  This can be done while the VM is running.

Will the VM try to decrease the balloon size before using swap space?

**Comment by YanVugenfirer** [comment] 2016-08-08 07:34
There is a Windows service that works with Balloon driver and reports
memory usage statistics in the VM. But I am not sure how management part
(libvirt for example) will handle it.

Best regards,
Yan.

**Comment by vrozenfe** [comment] 2016-08-08 10:38
AFAIR there were several attempts to implement auto-ballooning  in the past. I was surprised to see that  MOM ( http://www.ovirt.org/develop/projects/mom /)  is still alive. Maybe they finally managed to make it working (on Windows).

Cheers,
Vadim.

**Comment by vrozenfe** [comment] 2017-11-20 01:11
Seems to be fixed after installing the right driver.
Closing the issue.
Vadim.

**Comment by codemonkey76** [comment] 2020-08-13 02:09
I received this exact same issue using latest virtio-win-0.1.189 windows 7 64-bit (using the win7/amd64 balloon driver)

**Comment by Azur4** [comment] 2020-08-14 06:32
I got the same problem with virtio-win-0.1.189 on Windows 2008r2.

**Comment by vrozenfe** [comment] 2020-08-14 06:56
@codemonkey76 @Azur4 
Are you guys both getting 0x0000007E bug check error code?

**Comment by codemonkey76** [comment] 2020-08-14 07:10
Yep

**Comment by vrozenfe** [comment] 2020-08-14 07:22
@codemonkey76 
Can you please give a try to balloon driver from 187 and let me know if it is a regression or not?
Thanks,
Vadim.

**Comment by Azur4** [comment] 2020-08-14 08:01
Tested 189, 185 and 173 - same error

**Comment by vrozenfe** [comment] 2020-08-15 12:43
@Azur4 
Can you tell me the drivers version?

**Comment by Azur4** [comment] 2020-08-15 12:48
61.74.104.14100
![screen](https://user-images.githubusercontent.com/25566333/90312655-cf610680-df0e-11ea-9513-340123067543.PNG)

**Comment by myeyre** [comment] 2020-09-27 09:21
Same problem here with latest 61.81.104.17400 in virtio-win-0.1.189.iso.

**Comment by tombull** [comment] 2020-10-10 15:16
I can confirm this is a regression from 187 -> 189. If you completely delete 189 from the system and then install 187, then it works fine.

Complete uninstallation instructions (without using Linux to browse the disk image): 
* Search `C:\Windows\` for `balloon`, you will find one folder with the old driver in, under `System32\DriverStore\FileRepository`, and one copy of `balloon.sys` in `C:\Windows\System32\drivers`. Ignore the 'Windows Balloon' sound files.
* Take ownership of both the folder and it's subfolders and files, and the file (in explorer, right click > Properties > Security > Advanced > Owner > Edit)
* Change permissions on both the folder and the file (in explorer, right click > Properties > Security > Edit > Add... > Choose your user account or 'Administrators' > Tick 'full control'.)
* Delete both the folder and the file.
* Restart

**Comment by ybendito** [comment] 2020-10-13 08:24
@hammerg Probably due to 
https://github.com/virtio-win/kvm-guest-drivers-windows/commit/270d0191b4aae94ace8222a35214b1f4c2dd5801#diff-85bddc940b3f42fa3ebdf517fd1e27fb99694fdbe384fbedeece2ad09d93fb7d
Can you please check?

**Comment by vrozenfe** [comment] 2020-10-14 02:02
Guys, 
Please be advised that we will not be able to sign any pre-Win8 binaries with  Red Hat SHA-1 signature,
just because we don't have any valid SHA-1 cross-certificate for kernel signing anymore. (we don't have SHA-2 as well)

Thanks,
Vadim.

**Comment by hammerg** [comment] 2020-10-14 13:28
> @hammerg Probably due to
> [270d019#diff-85bddc940b3f42fa3ebdf517fd1e27fb99694fdbe384fbedeece2ad09d93fb7d](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/270d0191b4aae94ace8222a35214b1f4c2dd5801#diff-85bddc940b3f42fa3ebdf517fd1e27fb99694fdbe384fbedeece2ad09d93fb7d)
> Can you please check?

@ybendito Are you sure about it? I compiled and installed a driver based on a version without this commit and it seem to work.

Git bisect blames [986b0b79](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/986b0b7944f012085b6e5df95a342c93b32ff1ef).

Can you please check?

**Comment by ybendito** [comment] 2020-10-20 13:15
@tombull 
[176-Win7.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/5408878/176-Win7.zip)
Does the attached build solves the problem? (It should if I understand correctly what happened)
Thanks

**Comment by ybendito** [comment] 2020-10-21 07:12
[176-Win7.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/5413929/176-Win7.zip)
@tombull Added missing file

**Comment by tombull** [comment] 2020-10-21 14:38
@ybendito 
The second zip file works fine. Please note that every file in the zip is byte-for-byte identical to the files supplied in 187 apart from line endings in the `.inf` file... so same binary files, same reported versions, everything. It also includes an unused file named `176` that contains the text output of the COFF/PE dumper for the driver. 
The driver in 187 works fine (as reported above), and it takes a while to test (completely purging old driver using the instructions I supplied above before installing new driver)... so if you have further versions, it would easier to just test that the files are identical to the old versions before going through the full test like this time.

**Comment by ybendito** [comment] 2020-10-21 15:03
@tombull Thanks, I've missed that, I thought build 169 was shipped in 187. My mistake. Only problem with this driver is that it can't be installed on Win7 out of the box before updates.

**Comment by nathanshearer** [comment] 2021-04-12 03:32
On a fresh install of Windows Server 2008 R2, not updated, the virtio-win-0.1.189/Balloon/2k8R2/amd64/ balloon driver will cause a BSOD.

**Comment by alealexpro100** [comment] 2021-07-31 15:51
Tried to use build 126 on Windows Server 2008 R2 and it worked. Balloon driver installed successfully and didn't cause any BSOD.

**Comment by alealexpro100** [comment] 2021-07-31 16:06
#8

**Comment by YanVugenfirer** [comment] 2022-01-17 09:09
We are no longer supporting Windows 7 in master branch.

**Closed by YanVugenfirer** 2022-01-17 09:09 UTC
