### ISSUE TITLE
Latest virtio-win.iso (virtio-win-0.1.229.iso as of writing) doesn't work with Windows 8.1

### ISSUE THREAD

**Issue by github2099** [virtio-win/kvm-guest-drivers-windows#914] opened 2023-05-07 05:43 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour: 
1. Install Windows 8.1 VM
2. Install Guest Tool from any iso version 217 and up.

**Expected behavior**
Can install VIrtio FS and enables Folder Sharing.

**Screenshots**

![Screenshot from 2023-05-06 23-39-22](https://user-images.githubusercontent.com/49584984/236659909-9cab16e3-1abf-4948-ab45-af1e8676a4db.png)

![Screenshot from 2023-05-06 23-39-36](https://user-images.githubusercontent.com/49584984/236659912-79e531a3-2582-4916-8105-f80fe30dd5e9.png)

![Screenshot from 2023-05-06 23-39-46](https://user-images.githubusercontent.com/49584984/236659914-8d73b8ad-b375-4cf0-ae26-0b3982f3b40b.png)

**Host:**
 - Disto:  Pop!_OS
 - Kernel version  6.2.6
 - QEMU version 6.2.0 
 - libvirt version 8.0.0

**VM:**
 - Windows version  Windows 8.1
 - Which driver has a problem  Virtio FS
 - Driver version or commit hash that was used to build the driver  0.1.217 and up

**Additional context**

**Comment by github2099** [comment] 2023-05-07 05:50
As a side note, I tested many versions, only up to virtio-win-0.1.215.iso works

**Comment by github2099** [comment] 2023-05-08 10:09
As another note, though the virtio-win-0.1.215.iso works on WIndows 8, I am unable to transfer large files between host and guest.. I'm talking about 500 mb.

**Comment by viktor-prutyanov** [comment] 2023-05-08 10:30
> As another note, though the virtio-win-0.1.215.iso works on WIndows 8, I am unable to transfer large files between host and guest.. I'm talking about 500 mb.
> 

Please, try the latest version

**Comment by viktor-prutyanov** [comment] 2023-05-09 15:27
> -> Same issue with Win Server 2019.
> 
> > Please, try the latest version
> 
> I can't find a newer one. [virtio-win-0.1.229-1/](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.229-1/) seems to be the latest.

You've just talked about 0.1.215

**Comment by Pamalosebi** [comment] 2023-05-09 16:04
> You've just talked about 0.1.215

I am sorry if I have caused some confusion here.

The whole issue is about the irtio-win-0.1.229.iso. Then @github2099 correctly stated
that the latest working version was 0.1.215. Which I was able to reproduce.
So the problem is basically with every version since 0.1.215.

And I just wanted to add, that its not just Windows 8.1 its also on Windows Server 2019.

**Comment by viktor-prutyanov** [comment] 2023-05-15 07:08
Hi,

Could you please create a separate issue regarding the 500mb copying problem?

**Comment by github2099** [comment] 2023-05-16 23:16
> Could you please create a separate issue regarding the 500mb copying problem?

thanks, I have created #915 for the copying problem

**Comment by xiagao** [comment] 2023-05-18 05:31
@github2099  Seems this issue is resolved, could you close it? Thanks.

**Comment by xiagao** [comment] 2023-05-18 06:53
Which virtiofsd version did you use, virtiofsd-c version or rust version? 
virtiofsd c version isn't maintained upstream, therefore, it's better to test virtiofsd rust version.

Check virtiofs version:
# rpm -qf /usr/libexec/virtiofsd 
virtiofsd-1.5.0-1.el9.x86_64
# rpm -qf /usr/libexec/virtiofsd 
qemu-kvm-common-6.2.0-33.module+el8.xxx

**Comment by github2099** [comment] 2023-05-23 06:30
> 

I'm not using Fedora, the above commands don't work

**Comment by viktor-prutyanov** [comment] 2023-05-23 09:24
> I'm not using Fedora, the above commands don't work

```
virtiofsd --version
```

**Comment by viktor-prutyanov** [comment] 2023-05-27 17:43
Which virtiofsd and WinFsp versions do you have?

**Comment by github2099** [comment] 2023-08-24 21:05
I believe I'm using this WinFsp:
https://github.com/winfsp/winfsp/releases/tag/v2.0

**Comment by sergey-239** [comment] 2023-09-24 23:07
virtio-win-0.1.240-1 does not work with windows 8.1 as well (setup fails)

**Comment by xiagao** [comment] 2023-10-10 05:51
The setup failed with the latest internal virtio-win installer.
But it works to install the driver from device manager and the shared dir can be mounted in win8.1 guest.

**Comment by xiagao** [comment] 2023-10-10 05:53
> The setup failed with the latest internal virtio-win installer. But it works to install the driver from device manager and the shared dir can be mounted in win8.1 guest.

winfsp-1.12.22339
virtio-win-0.1-240
win8.1-build 9600

**Closed** 2024-12-02 14:38 UTC
Labels: Bug, virtio-fs
