### ISSUE TITLE
When hotplug CPUs to Windows 2022 with multiple virtio-blk disks, the operating system freeze.

### ISSUE THREAD

**Issue by york-king** [virtio-win/kvm-guest-drivers-windows#904] opened 2023-04-17 08:05 UTC
**Describe the bug**
When hotplug CPUs to Windows 2022 with multiple virtio-blk disks, the operating system freeze.

**To Reproduce**
Steps to reproduce the behaviour:
1. Windows 2022 uses more than one disks;
2. After hotplug CPUs, Disk I/O stuck;

**Expected behavior**
null

**Screenshots**
null

**Host:**
 - Kernel version
4.18.0
 - QEMU version
5.0

**VM:**
 - Windows version
windows 2022 Standard
 - Which driver has a problem
 viostor
 - Driver version or commit hash that was used to build the driver
 DriverVer = 11/15/2022,100.92.104.22900
 driver is download form:
 https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.229-1/

**Additional context**
use ide disks，hotplug CPUs is ok.

**Comment by vrozenfe** [comment] 2023-04-17 13:00
@york-king 

Can you please provide the qemu command line?

Thanks,
Vadim.

**Comment by york-king** [comment] 2023-04-18 13:55
> 
qemu command line :

/usr/libexec/qemu-kvm
-name guest=b48aca5c-b534-441f-b489-a0237e6ad7cf,debug-threads=on
-uuid 609c5003-d446-4d51-9ff4-18955c939699
-mem-prealloc
-m size=4194304k,slots=255,maxmem=4194304000k
-object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-20-b48aca5c-b534-441f-b/master-key.aes
-object memory-backend-file,id=ram-node0,prealloc=yes,mem-path=/dev/hugepages/libvirt/qemu/20-b48aca5c-b534-441f-b,share=yes,size=4294967296
-numa node,nodeid=0,cpus=0-239,memdev=ram-node0
-device pci-bridge,chassis_nr=1,id=pci.1,bus=pci.0,addr=0x3
-device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2
-device nec-usb-xhci,p2=15,p3=15,id=usb1,bus=pci.0,addr=0x5
-device usb-ehci,id=usb2,bus=pci.0,addr=0x6
-device piix3-usb-uhci,id=usb3,bus=pci.0,addr=0x7
-device virtio-serial-pci,id=virtio-serial0,max_ports=2,bus=pci.0,addr=0x8
-device virtio-net-pci,mq=on,vectors=10,rx_queue_size=1024,netdev=hostnet0,id=net0,mac=52:54:00:ed:5e:96,bus=pci.0,addr=0x4
-device isa-serial,chardev=charserial0,id=serial0
-device isa-serial,chardev=charserial1,id=serial1
-device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0
-device usb-tablet,id=input1,bus=usb.0,port=1
-device cirrus-vga,id=video0,bus=pci.0,addr=0x2
-device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0xc
-device vhost-user-blk-pci,bus=pci.0,addr=0x9,chardev=drive-virtio-disk0,id=virtio-disk0,num-queues=1,bootindex=1
-device vhost-user-blk-pci,bus=pci.0,addr=0xa,chardev=drive-virtio-disk1,id=virtio-disk1,num-queues=1,bootindex=2
-device vhost-user-blk-pci,bus=pci.0,addr=0xb,chardev=drive-virtio-disk2,id=virtio-disk2,num-queues=1,bootindex=3
-chardev socket,id=charmonitor,path=/var/run/procurator/monitor/monitor-b48aca5c-b534-441f-b489-a0237e6ad7cf.sock,server,nowait
-chardev pty,id=charserial0
-chardev file,id=charserial1,path=/dev/fdset/9,append=on
-chardev socket,id=charchannel0,fd=51,server,nowait
-chardev socket,id=drive-virtio-disk0,path=/var/run/procurator/vhost/vhost-blk.b48aca5c-b534-441f-b489-a0237e6ad7cf.1
-chardev socket,id=drive-virtio-disk1,path=/var/run/procurator/vhost/vhost-blk.b48aca5c-b534-441f-b489-a0237e6ad7cf.2
-chardev socket,id=drive-virtio-disk2,path=/var/run/procurator/vhost/vhost-blk.b48aca5c-b534-441f-b489-a0237e6ad7cf.3
-S
-machine pc-i440fx-rhel7.6.0,accel=kvm,usb=off,dump-guest-core=off
-cpu Broadwell-IBRS
-realtime mlock=off
-smp 2,maxcpus=240,sockets=120,cores=2,threads=1
-smbios type=1,manufacturer=SmartX,product=SMTX OS,version=1.0,serial=SmartX-5cca8ab434b51f44-b489a0237e6ad7cf
-no-user-config
-nodefaults
-mon chardev=charmonitor,id=monitor,mode=control
-rtc base=utc
-no-shutdown
-boot menu=on,strict=on
-netdev tap,fds=43:44:45:46,id=hostnet0,vhost=on,vhostfds=47:48:49:50
-add-fd set=9,fd=52
-vnc 127.0.0.1:1
-rtc driftfix=slew,clock=rt
-sandbox off
-msg timestamp=on

**Comment by vrozenfe** [comment] 2023-04-20 03:28
Thanks a lot york,

Let me try to reproduce this issue on my system.
Did you run any disk stress test during the CPU hotplug?
And do you have any particular reasons for not enabling multi-queue 
for the viostor devices?

Best,
Vadim.

**Comment by york-king** [comment] 2023-04-20 06:56
Hi  Vadim,

1. I did not run disk stress testing during CPU hotplug. This is a newly installed Windows 2022 virtual machine without running any tools. The problem occurs after hotplug CPU once or multiple times.
2. How can I enable multi-queue for the viostor devices?

Thanks,
York

**Comment by vrozenfe** [comment] 2023-04-20 10:01
Hi York

viostor (virtio-blk-pci / vhost-user-blk-pci) should be capable to run in multi-queue mode.
multi-queue can be activated by specifying "num-queues" equal to number of vCPUs
-device vhost-user-blk-pci,bus=pci.0,addr=0x9,chardev=drive-virtio-disk0,id=virtio-disk0,num-queues=1,bootindex=1
                                                                                                                                                ^^^^^^^^^^
but it will not be scaled up after vCPU hot-plug in any case.
But never mind, I was just wondering if there is any particular reason for not enabling it by default.

Best,
Vadim.

**Comment by york-king** [comment] 2023-04-22 09:28
Hi Vadim,

Do you reproduce this issue ?
I make a windows memory dump: [https://www.aliyundrive.com/s/s3f6fLTLsmE]

Windbg prompts "Possible deadlock. Use !locks FFFFF8055E650280 to determine the resource owner"

After hotplug CPUs,  the viostor driver inserts a DPC, but why does this DPC never return?

![image](https://user-images.githubusercontent.com/55568212/233775375-d012347b-dbc3-4dcf-9f29-099dbece1c3f.png)

![image](https://user-images.githubusercontent.com/55568212/233775435-67557021-be78-47b9-bebe-44f60c33a7cf.png)

Best,
York

**Comment by vrozenfe** [comment] 2023-04-24 13:24
Hi York,
I didn't have time to look into this matter yet. Going to to do that in a couple of days or so,
I remember we tested cpu hot-plug with multiqueue many times in the past. To the best 
of my knowledge it should work, unless something has been broken recently. Honestly, we don't
test single queue mode since it is not an optimal operating mode, In any case, I'm going to check
this issue shortly.
Thank you for sharing the crash dump file and for doing the dump analysis.
Best regards,
Vadim.

**Comment by menli820** [comment] 2023-04-26 03:39
Hi York,

Thanks for reporting this issue.
We have an open bug currently (https://bugzilla.redhat.com/show_bug.cgi?id=2178384#c3 )
It is related to USB.

So could you please try to remove '-device piix3-usb-uhci,id=usb -device usb-tablet,id=input1 \' to see whether this workaround works for you?


Thanks 
Menghuan

**Comment by menli820** [comment] 2023-04-28 14:59
Hi York,

I can reproduce the issue and have some other information to share.

reproduce step:
1. boot win2022 guest with the following qemu command line.
 /usr/libexec/qemu-kvm \
    -name 'upstream' \
    -machine pc \
    -nodefaults \
    -device VGA,bus=pci.0 \
    -blockdev node-name=file_sys,driver=file,cache.direct=on,cache.no-flush=off,filename=win2022-64-virtio.qcow2,aio=threads \
    -blockdev node-name=drive_sys,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_sys \
    -device virtio-blk-pci,id=sys,drive=drive_sys,bus=pci.0,**num-queues=1** \
    -blockdev node-name=file_stg1,driver=file,cache.direct=on,cache.no-flush=off,filename=stgtest1.qcow2,aio=threads \
    -blockdev node-name=drive_stg1,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_stg1 \
    -device virtio-blk-pci,id=stg1,drive=drive_stg1,bus=pci.0 \
    -blockdev node-name=file_stg2,driver=file,cache.direct=on,cache.no-flush=off,filename=stgtest2.qcow2,aio=threads \
    -blockdev node-name=drive_stg2,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_stg2 \
    -device virtio-blk-pci,id=stg2,drive=drive_stg2,bus=pci.0 \
    -device virtio-net-pci,mac=9a:36:83:b6:3d:05,id=idJVpmsF,netdev=id23ZUK6,bus=pci.0  \
    -netdev tap,id=id23ZUK6,vhost=on,script=/etc/qemu-ifup \
    -m 14336  \
    -smp 4,maxcpus=6,cores=3,threads=1,dies=1,sockets=2 \
    -cpu 'Skylake-Server' \
    -vnc :10  \
    -rtc base=localtime,clock=host,driftfix=slew  \
    -boot order=cdn,once=c,menu=off,strict=off \
    -enable-kvm \
    -qmp tcp:0:1212,server,nowait \
    -monitor stdio \

3.  Do Cpu hotplug on qmp monitor: 
eg： { "execute": "device_add","arguments":{"driver":"Icelake-Server-noTSX-x86_64-cpu","core-id": 1, "thread-id": 0, "socket-id": 1,"id":"cpu2" }}

actual result:
After step3 the system freezes.

Additional info:
remove 'num-queues=1' from above  command line, repeat the above steps , the guest can work(but the system got stuck for some seconds sometimes)

so it also related to 'num-queues=1' .

Got the dump file via command ： dump-guest-memory -w /var/tmp/z1qzMemory.dmp
dump link:
http://fileshare.hosts.qa.psi.pek2.redhat.com/pub/section2/coredump/upstream904/

cc @vrozenfe 


Thanks
Menghuan

**Comment by menli820** [comment] 2023-04-28 15:01
Hi York,

I can reproduce the issue and have some other information to share.

reproduce step:
1. boot win2022 guest with the following qemu command line.
 /usr/libexec/qemu-kvm \
    -name 'upstream' \
    -machine pc \
    -nodefaults \
    -device VGA,bus=pci.0 \
    -blockdev node-name=file_sys,driver=file,cache.direct=on,cache.no-flush=off,filename=win2022-64-virtio.qcow2,aio=threads \
    -blockdev node-name=drive_sys,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_sys \
    -device virtio-blk-pci,id=sys,drive=drive_sys,bus=pci.0,**num-queues=1** \
    -blockdev node-name=file_stg1,driver=file,cache.direct=on,cache.no-flush=off,filename=stgtest1.qcow2,aio=threads \
    -blockdev node-name=drive_stg1,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_stg1 \
    -device virtio-blk-pci,id=stg1,drive=drive_stg1,bus=pci.0 \
    -blockdev node-name=file_stg2,driver=file,cache.direct=on,cache.no-flush=off,filename=stgtest2.qcow2,aio=threads \
    -blockdev node-name=drive_stg2,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_stg2 \
    -device virtio-blk-pci,id=stg2,drive=drive_stg2,bus=pci.0 \
    -device virtio-net-pci,mac=9a:36:83:b6:3d:05,id=idJVpmsF,netdev=id23ZUK6,bus=pci.0  \
    -netdev tap,id=id23ZUK6,vhost=on,script=/etc/qemu-ifup \
    -m 14336  \
    -smp 4,maxcpus=6,cores=3,threads=1,dies=1,sockets=2 \
    -cpu 'Skylake-Server' \
    -vnc :10  \
    -rtc base=localtime,clock=host,driftfix=slew  \
    -boot order=cdn,once=c,menu=off,strict=off \
    -enable-kvm \
    -qmp tcp:0:1212,server,nowait \
    -monitor stdio \

3.  Do Cpu hotplug on qmp monitor: 
eg： { "execute": "device_add","arguments":{"driver":"Icelake-Server-noTSX-x86_64-cpu","core-id": 1, "thread-id": 0, "socket-id": 1,"id":"cpu2" }}

actual result:
After step3 the system freezes.

Additional info:
remove 'num-queues=1' from above  command line, repeat the above steps , the guest can work(but the system got stuck for some seconds sometimes)

so it also related to 'num-queues=1' .

Got the dump file via command ： dump-guest-memory -w /var/tmp/z1qzMemory.dmp
dump link:
http://fileshare.hosts.qa.psi.pek2.redhat.com/pub/section2/coredump/upstream904/

cc @vrozenfe 


Thanks
Menghuan

**Comment by annie-li** [comment] 2023-05-03 21:22
I am also running into a hang issue in Windows 2016 VM. The guest hangs after user hot plugs one vioblk disk and then vcpus. Hot plugging vcpus first and then vioblk device is fine. Looks like this issue is similar to the issue here.
FYI, I've implemented a patch to fix this issue on my side, and created a pull request - https://github.com/virtio-win/kvm-guest-drivers-windows/pull/913.

**Comment by menli820** [comment] 2023-05-04 09:32
Thanks for the info.
reproduce a similar issue with the following steps.

How reproducible:
100%

Guest: Win2022
kernel-5.14.0-162.6.1.el9_1.x86_64
qemu-kvm-7.0.0-13.el9.x86_64
seabios-bin-1.16.0-4.el9.noarch
virtio-win-prewhql-235

1. Boot guest with following steps

 /usr/libexec/qemu-kvm \
    -name 'upstream' \
    -machine pc \
    -nodefaults \
    -device VGA,bus=pci.0 \
    -blockdev node-name=file_sys,driver=file,cache.direct=on,cache.no-flush=off,filename=win2022-64-virtio.qcow2,aio=threads \
    -blockdev node-name=drive_sys,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_sys \
    -device virtio-blk-pci,id=sys,drive=drive_sys,bus=pci.0,num-queues=1 \
    -device virtio-net-pci,mac=9a:36:83:b6:3d:05,id=idJVpmsF,netdev=id23ZUK6,bus=pci.0  \
    -netdev tap,id=id23ZUK6,vhost=on,script=/etc/qemu-ifup \
    -m 14336  \
    -smp 5,maxcpus=10,cores=5,threads=1,dies=1,sockets=2  \
    -cpu 'Skylake-Server' \
    -vnc :10  \
    -rtc base=localtime,clock=host,driftfix=slew  \
    -boot order=cdn,once=c,menu=off,strict=off \
    -enable-kvm \
    -qmp tcp:0:1212,server,nowait \
    -monitor stdio \
    -device vmcoreinfo \

2. hotplug virtio-blk device

(qemu) drive_add auto file=/home/kvm_autotest_root/images/storage0.raw,format=raw,if=none,id=test1,cache=none
OK
(qemu) device_add virtio-blk-pci,drive=test1,id=test-disk,bus=pci.0

3.  Do Cpu hotplug on qmp monitor:
{"execute": "qmp_capabilities"}
{"execute": "device_add", "arguments": {"id": "vcpu1", "driver": "Skylake-Server-x86_64-cpu", "socket-id": 1, "die-id": 0, "core-id": 0, "thread-id": 0}, "id": "vUKklSbQ"}

4.  hotplug virtio-blk device
(qemu) drive_add auto file=/home/kvm_autotest_root/images/storage1.raw,format=raw,if=none,id=test2,cache=none
OK
(qemu) device_add virtio-blk-pci,drive=test2,id=test-disk2,bus=pci.0

Actual result:
Guest hang.


Thanks
Menghuan

**Comment by menli820** [comment] 2023-05-05 01:31
> I am also running into a hang issue in Windows 2016 VM. The guest hangs after user hot plugs one vioblk disk and then vcpus. Hot plugging vcpus first and then vioblk device is fine. Looks like this issue is similar to the issue here. FYI, I've implemented a patch to fix this issue on my side, and created a pull request - #913.

@annie-li  Thanks for this info, I can reproduce with win2022 but didn't hit it with Win2016,  so could you please help paste your qemu command line and package Versions?

**Comment by annie-li** [comment] 2023-05-05 19:32
@menli820 Have you tired to apply my patch in [#913](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/913) to see if this patch fixes the issue in your Win2022?
I can reproduce this hang issue in both Win2016 and Win2022 from my side. With the patch applied, the hang issue is gone for both VMs. Please refer to the following command that I've been using for Win2016 VM(same command line used for Win2022 VM),
`/usr/bin/qemu-system-x86_64 \
-name WindowsServer2016-uefi \
-machine q35,accel=kvm \
-cpu host,+host-phys-bits,hv-relaxed,hv-time \
-smp 16,maxcpus=255 \
-m 32G \
-monitor stdio \
-vnc :0 \
-usb -device usb-tablet,id=tablet1 \
-device VGA \
-nodefaults \
-serial telnet:127.0.0.1:44441,server=on,wait=off \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=1,id=pciroot1,bus=pcie.0,addr=10.00,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=2,id=pciroot2,bus=pcie.0,addr=10.01,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=3,id=pciroot3,bus=pcie.0,addr=10.02,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=4,id=pciroot4,bus=pcie.0,addr=10.03,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=5,id=pciroot5,bus=pcie.0,addr=10.04,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=6,id=pciroot6,bus=pcie.0,addr=10.05,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=7,id=pciroot7,bus=pcie.0,addr=10.06,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=8,id=pciroot8,bus=pcie.0,addr=10.07,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=9,id=pciroot9,bus=pcie.0,addr=11.00,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=10,id=pciroot10,bus=pcie.0,addr=11.01,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=11,id=pciroot11,bus=pcie.0,addr=11.02,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=12,id=pciroot12,bus=pcie.0,addr=11.03,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=13,id=pciroot13,bus=pcie.0,addr=11.04,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=14,id=pciroot14,bus=pcie.0,addr=11.05,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=15,id=pciroot15,bus=pcie.0,addr=11.06,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=16,id=pciroot16,bus=pcie.0,addr=11.07,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=17,id=pciroot17,bus=pcie.0,addr=12.00,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=18,id=pciroot18,bus=pcie.0,addr=12.01,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=19,id=pciroot19,bus=pcie.0,addr=12.02,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=20,id=pciroot20,bus=pcie.0,addr=12.03,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=21,id=pciroot21,bus=pcie.0,addr=12.04,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=22,id=pciroot22,bus=pcie.0,addr=12.05,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=23,id=pciroot23,bus=pcie.0,addr=12.06,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=24,id=pciroot24,bus=pcie.0,addr=12.07,multifunction=on \
-device pcie-root-port,io-reserve=0,pref64-reserve=32M,chassis=25,id=pciroot25,bus=pcie.0,addr=13.00,multifunction=on \
-drive file=/usr/share/OVMF/OVMF_CODE.pure-efi.fd,index=0,if=pflash,format=raw,readonly \
-drive file=/usr/share/OVMF/OVMF_VARS.pure-efi.fd,index=1,if=pflash,format=raw,readonly \
-global ICH9-LPC.disable_s3=1 \
-chardev pty,id=charserial1 \
-device isa-serial,chardev=charserial1,id=serial1 \
-netdev tap,id=net8,vhost=on,fd=10 10<>/dev/tap82 \
-device e1000,netdev=net8,id=hostnet8,mac=7e:b1:fb:99:a2:14 \
-drive file=/mnt1/win2016/WindowsServer2016-uefi.qcow2,format=qcow2,if=none,id=drive0 \
-device ide-hd,drive=drive0,id=disk0,bootindex=1 \
-rtc base=localtime,clock=host,driftfix=slew \
-qmp tcp:localhost:55557,server=on,wait=off \
-qmp unix:/tmp/qmpsocket7,server=on,wait=off \
-monitor unix:/tmp/tt7,server=on,wait=off`

**Comment by annie-li** [comment] 2023-05-10 16:07
@york-king perfect! Please consider closing this ticket since the patch has fixed your issue.

**Closed** 2023-05-11 01:29 UTC
Labels: Bug, viostor
