### ISSUE TITLE
cannot boot windows 7 with qxl drivers

### ISSUE THREAD

**Issue by muelli** [virtio-win/kvm-guest-drivers-windows#244] opened 2018-01-28 18:20 UTC
I have a vanilla windows 7 from modern.ie (apparently "version 20150916") and once I install the QXL driver from  virtio-win-0.1.141.iso
(43aefa812c37342cfefc48ec0dd7f1e56a930fcd) the machine doesn't boot anymore.  The situation doesn't change if I install all the available Windows updates.

`STOP 0x0000007F (0x0000000D, 0x0, 0x0, 0x0)`

According to https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x7f--unexpected-kernel-mode-trap it indicates a "Bug Check 0x7F: UNEXPECTED_KERNEL_MODE_TRAP" with "0x0000000D -- An exception not covered by some other exception; a protection fault that pertains to access violations for applications".

Once I change the video mode from QXL to, say, virtio, I can boot.

I thus suspect the QXL driver to be the cuprit.
Interestingly, using the "Windows guest tools - spice-guest-tools" from https://www.spice-space.org/download.html seems to work better. But it's unfortunate to download the stuff from there, because it requires a network connection. And Windows does not have virtio network drivers by default.

**Comment by sameehj** [comment] 2018-01-29 01:01
Hi @muelli ,

In order to debug this efficiently  can you please provide me with the following information:
 * Command line for running the machine?
 * Qemu version

I want to try and reproduce this,
Thanks for reporting the issue =)

**Comment by muelli** [comment] 2018-01-29 11:25
I managed to reproduce like this. 

I booted the vanilla image off modern.ie: `b84bbeb6ef1acd71819ab2eea12ea535b39a5f9b  win7-ie11.vanilla.qcow2`

through virt-manager, which seems to call out like that:

`qemu-system-x86_64 -enable-kvm -name guest=win7,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=~/.config/libvirt/qemu/lib/domain-14-win7/master-key.aes -machine pc-i440fx-artful,accel=kvm,usb=off,vmport=off,dump-guest-core=off -cpu qemu64,hv_time,hv_relaxed,hv_vapic,hv_spinlocks=0x1fff -m 4096 -realtime mlock=off -smp 1,sockets=1,cores=1,threads=1 -uuid d8278e6e-8583-4722-90d1-ef84b580ffeb -no-user-config -nodefaults -chardev socket,id=charmonitor,path=~/.config/libvirt/qemu/lib/domain-14-win7/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=localtime,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x5.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x5 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x5.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x5.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x6 -drive file=~/.local/share/libvirt/images/win7-ie11.qcow2,format=qcow2,if=none,id=drive-ide0-0-0 -device ide-hd,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0,bootindex=1 -drive file=~/.local/share/libvirt/images/virtio-win.iso,format=raw,if=none,id=drive-ide0-0-1,readonly=on -device ide-cd,bus=ide.0,unit=1,drive=drive-ide0-0-1,id=ide0-0-1 -netdev user,id=hostnet0 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:72:bc:69,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -device usb-tablet,id=input0,bus=usb.0,port=1 -spice port=5900,addr=127.0.0.1,disable-ticketing,image-compression=off,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pci.0,addr=0x8 -device virtio-gpu-pci,id=video1,bus=pci.0,addr=0x2 -device intel-hda,id=sound0,bus=pci.0,addr=0x4 -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=3 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=4 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x7 -msg timestamp=on
`

the XML looks like this:

```
<domain type='kvm' id='14'>
  <name>win7</name>
  <uuid>d8278e6e-8583-4722-90d1-ef84b580ffeb</uuid>
  <memory unit='KiB'>4194304</memory>
  <currentMemory unit='KiB'>4194304</currentMemory>
  <vcpu placement='static'>1</vcpu>
  <os>
    <type arch='x86_64' machine='pc-i440fx-artful'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
      <relaxed state='on'/>
      <vapic state='on'/>
      <spinlocks state='on' retries='8191'/>
    </hyperv>
    <vmport state='off'/>
  </features>
  <clock offset='localtime'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
    <timer name='hypervclock' present='yes'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/kvm-spice</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='~/.local/share/libvirt/images/win7-ie11.qcow2'/>
      <backingStore/>
      <target dev='hda' bus='ide'/>
      <alias name='ide0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='~/.local/share/libvirt/images/virtio-win.iso'/>
      <backingStore/>
      <target dev='hdb' bus='ide'/>
      <readonly/>
      <alias name='ide0-0-1'/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
    <controller type='usb' index='0' model='ich9-ehci1'>
      <alias name='usb'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x7'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci1'>
      <alias name='usb'/>
      <master startport='0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0' multifunction='on'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci2'>
      <alias name='usb'/>
      <master startport='2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x1'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci3'>
      <alias name='usb'/>
      <master startport='4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'>
      <alias name='pci.0'/>
    </controller>
    <controller type='ide' index='0'>
      <alias name='ide'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <alias name='virtio-serial0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </controller>
    <interface type='user'>
      <mac address='52:54:00:72:bc:69'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <source path='/dev/pts/3'/>
      <target port='0'/>
      <alias name='serial0'/>
    </serial>
    <console type='pty' tty='/dev/pts/3'>
      <source path='/dev/pts/3'/>
      <target type='serial' port='0'/>
      <alias name='serial0'/>
    </console>
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0' state='disconnected'/>
      <alias name='channel0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='tablet' bus='usb'>
      <alias name='input0'/>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'>
      <alias name='input1'/>
    </input>
    <input type='keyboard' bus='ps2'>
      <alias name='input2'/>
    </input>
    <graphics type='spice' port='5900' autoport='yes' listen='127.0.0.1'>
      <listen type='address' address='127.0.0.1'/>
      <image compression='off'/>
    </graphics>
    <sound model='ich6'>
      <alias name='sound0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </sound>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
      <alias name='video0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
    </video>
    <video>
      <model type='virtio' heads='1'/>
      <alias name='video1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <redirdev bus='usb' type='spicevmc'>
      <alias name='redir0'/>
      <address type='usb' bus='0' port='3'/>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
      <alias name='redir1'/>
      <address type='usb' bus='0' port='4'/>
    </redirdev>
    <memballoon model='virtio'>
      <stats period='5'/>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </memballoon>
  </devices>
  <seclabel type='none' model='none'/>
</domain>

```


Note that I have two graphics adapters because I thought I'd have a fallback in addition to the QXL one.

After the first boot it installs some drivers and wants to restart. Then it comes up and has a few drivers missing. Fair enough. I install them from the attached CD-ROM drive. Except for the "Video Controller"! That somehow fails.  ![screenshot from 2018-01-29 11-32-34](https://user-images.githubusercontent.com/322807/35507895-921ea644-04ee-11e8-8e6a-817a5761f5d5.png)

After another reboot I force the installation of updates through the settings panel
![screenshot from 2018-01-29 11-58-58](https://user-images.githubusercontent.com/322807/35507939-bdef183a-04ee-11e8-9afc-df54eb57a9da.png)

After a reboot I installed the guest agent 
![screenshot from 2018-01-29 12-09-13](https://user-images.githubusercontent.com/322807/35507957-d5746ab4-04ee-11e8-971a-96aa528191c6.png)

I then install the QXL driver by updating the driver for the "default video adapter" or something.
![screenshot from 2018-01-29 12-12-49](https://user-images.githubusercontent.com/322807/35508004-0b9c4b5c-04ef-11e8-85d6-326835ab8e41.png)

Then I remove the virtio graphics adapter through virt-manager, press "reboot", and I see it failing when it tried to start:
![screenshot from 2018-01-29 12-13-42](https://user-images.githubusercontent.com/322807/35508034-2b0abe7e-04ef-11e8-9b2c-e69eb1507df9.png)

I could potentially give you access to the qcow file if you think you need it. It's about 15GB in size. It boots happily when using virtio as the only graphical adapter.

**Comment by sameehj** [comment] 2018-01-29 11:36
Hi @muelli ,

Thanks for all of this info, I just need one more thing. Can you please share the dump file with us and the driver package that you used. 

you can configure windows to save dumps this way:
https://image.slidesharecdn.com/windowsguestdebugging-kvmforum2012-130204094652-phpapp02/95/windows-guest-debugging-presentation-from-kvm-forum-2012-31-638.jpg?cb=1434356706

and then grab the dump file from where it usually resides in c:\Windows\memory.dmp

Thanks!

**Comment by muelli** [comment] 2018-01-29 11:50
The 100MB memory dump is here:  https://send.firefox.com/download/6b8e1e1989/#MCuJ8hlDPNMF-t38i8zOqQ

first click first serve...  If you have a suggestion as to where to place that file, I'm happy to upload it there.

> Can you also please indicate from what directory you are installing the driver?

I don't understand.  I selected "search my local computer" and then "D:\" for the CD-ROM drive. I only ever had it install drivers off the CD-ROM drive.

**Comment by ybendito** [comment] 2018-01-29 12:19
Looks like by misunderstanding you try to use qxldod driver for Win10.
On Win7 should be used qxl driver for Win7, it is on CD under qxl/w7 directory

**Comment by muelli** [comment] 2018-01-29 12:35
> Looks like by misunderstanding you try to use qxldod driver for Win10.

hm. Again: I haven't manually selected any driver in particular. I've only ever given it "d:\" as a path.


I don't know how to test this now, because I can only boot when the QXL adapter is not present. Then, however, I don't know how to update the QXL driver, because I have nowhere to click "update driver". I could start over with a fresh machine, but maybe we need the current machine still.

I'd consider it a bug if it's selecting the wrong driver, anyway. Maybe it's a Microsoft bug, though.

**Comment by ybendito** [comment] 2018-01-29 12:43
You can uninstall the qxldod driver: boot the machine without qxl, then open device manager, select 'show hidden devices', find the QXL adapter and select 'Uninstall' and check 'Remove driver'. On next boot with qxl it will be installed with standard MSFT driver, then you can install proper driver for it.

**Comment by YanVugenfirer** [comment] 2018-01-29 12:44
On Mon, Jan 29, 2018 at 2:35 PM, muelli <notifications@github.com> wrote:

> Looks like by misunderstanding you try to use qxldod driver for Win10.
>
> hm. Again: I haven't manually selected any driver in particular. I've only
> ever given it "d:" as a path.
>
You should select the correct driver for the correct platform.


> I don't know how to test this now, because I can only boot when the QXL
> adapter is not present. Then, however, I don't know how to update the QXL
> driver, because I have nowhere to click "update driver". I could start over
> with a fresh machine, but maybe we need the current machine still.
>
Remove the driver using device manager or other tool.

> I'd consider it a bug if it's selecting the wrong driver, anyway. Maybe
> it's a Microsoft bug, though.
>
This is a way that Windows selects the INFs. It will get the first one it
will found.

**Comment by muelli** [comment] 2018-01-29 12:51
> then open device manager, select 'show hidden d then open device manager, select 'show hidden devices', find the QXL adapter and select 'Uninstall' and check 'Remove driver'evices', find the QXL adapter and select 'Uninstall' and check 'Remove driver'

I cannot find such a device.



> You should select the correct driver for the correct platform.

Is it not possible to ship multiple drivers on the CD-ROM and have Windows select the most appropriate one?
If its not, would it be possible to include the .exe from https://www.spice-space.org/download.html on the CD-ROM? That executable seems to work well.

**Comment by ybendito** [comment] 2018-01-29 13:52
With 'show hidden devices' you should see two devices under 'display adapters' - one existing, one not existing, not existing is the one you need to uninstall together with the driver.

**Comment by muelli** [comment] 2018-01-29 13:56
![screenshot from 2018-01-29 14-54-41](https://user-images.githubusercontent.com/322807/35513825-95734ec4-0504-11e8-9b15-971b90cb4905.png)
![screenshot from 2018-01-29 14-54-53](https://user-images.githubusercontent.com/322807/35513826-95c08d92-0504-11e8-8694-66efaf4d0bd1.png)
![screenshot from 2018-01-29 14-55-02](https://user-images.githubusercontent.com/322807/35513828-95eb6fee-0504-11e8-90ad-3c73f32e2591.png)
![screenshot from 2018-01-29 14-55-11](https://user-images.githubusercontent.com/322807/35513829-960d2e4a-0504-11e8-83da-0ac40bd165de.png)
![screenshot from 2018-01-29 14-55-43](https://user-images.githubusercontent.com/322807/35513830-96505e68-0504-11e8-82d5-89f88c650155.png)

**Comment by muelli** [comment] 2018-01-29 19:08
ah, with "scan for hardware changes" it detected a standard VGA adapter. Sorry, my Windows-fu isn't very strong.
I uninstalled that new device and try to reboot, but it showed the "Shutting down" screen forever. I forced the machine off and rebooted with a QXL adapter instead of virtio and it booted successfully.  It still had a standard VGA compatible adapter and I selected to to update the driver from "D:\QXL\W7".
I then updated the driver and it successfully rebooted.

I appreciate that manually selecting the driver makes this a non-issue. But it's hard for me to tell whether it installs the correct driver.
My life would be a tiny bit happier if I didn't have to manually select this particular driver while all the others seem to install fine when Windows is pointed to the root of the CD-ROM.

**Comment by YanVugenfirer** [comment] 2018-01-29 19:17
Glad to hear it worked out for you.

In any case, while other drivers might function (for example if you install
Windows XP driver on Windows 7 for network adapter) - they might not
function in an optimal way.

Best regards,
Yan.

**Comment by muelli** [comment] 2018-02-07 12:28
What's the rationale for closing?

I still think that the experience could be better and maybe investigating the shipping of multiple drivers on the CD-ROM and have Windows select the most appropriate one is one option to make it better. Another might be to include the .exe from https://www.spice-space.org/download.html on the CD-ROM.
You have more knowledge than me in these areas, so I think it's worth sharing that with the closure of this issue.

**Comment by sameehj** [comment] 2018-02-07 13:07
I have opened a bug report in the following link:
https://bugzilla.redhat.com/show_bug.cgi?id=1542909

This is not the right place to track this issue, I will update once the bug is resolved.
Thanks!

**Comment by sameehj** [comment] 2018-02-07 15:03
@muelli Hi

I have tried to reproduce the issue but I could not, even when selecting the qxldod folder instead of the parent folder which has both qxl and qxldod. Windows doesnt select a driver from the qxldod. Can you please try and point to d:\qxldod and try and install the driver? Does this succeeds?

**Comment by muelli** [comment] 2018-02-20 17:18
This is 100% reproducible for me.

I've visited https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and selected IE11 on Win7 for Vagrant. The download link is https://az792536.vo.msecnd.net/vms/VMBuild_20150916/Vagrant/IE11/IE11.Win7.Vagrant.zip and my sha256sum is `08fcafe549ecffb012de008f2b20930cd6670902bc786d5ab1517862ed478738  /tmp/IE11.Win7.Vagrant.zip`.
I unpacked the zip file and untarred the resulting .box file. I then `qemu-img convert -f vmdk /tmp/box-disk1.vmdk  -O qcow2 win7-ie11.qcow2`. Then I `virsh define /tmp/win7.xml --validate` with the following XML:

```
<domain type='kvm'>
  <name>win7-crash</name>
  <uuid>d8278e6e-8583-4722-9ff1-ef8ffff0ffeb</uuid>
  <memory unit='KiB'>4194304</memory>
  <currentMemory unit='KiB'>4194304</currentMemory>
  <vcpu placement='static'>1</vcpu>
  <os>
    <type arch='x86_64' machine='pc-i440fx-artful'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
      <relaxed state='on'/>
      <vapic state='on'/>
      <spinlocks state='on' retries='8191'/>
    </hyperv>
    <vmport state='off'/>
  </features>
  <clock offset='localtime'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
    <timer name='hypervclock' present='yes'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/kvm-spice</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/home/muelli/.local/share/libvirt/images/win7-ie11-crash.qcow2'/>
      <target dev='hda' bus='ide'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/home/muelli/.local/share/libvirt/images/virtio-win.iso'/>
      <target dev='hdb' bus='ide'/>
      <readonly/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
    <controller type='usb' index='0' model='ich9-ehci1'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x7'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci1'>
      <master startport='0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0' multifunction='on'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci2'>
      <master startport='2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x1'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci3'>
      <master startport='4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'/>
    <controller type='ide' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </controller>
    <interface type='user'>
      <mac address='52:54:00:72:bc:69'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <channel type='spiceport'>
      <source channel='org.spice-space.webdav.0'/>
      <target type='virtio' name='org.spice-space.webdav.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='2'/>
    </channel>
    <input type='tablet' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='spice' autoport='yes'>
      <listen type='address'/>
      <image compression='off'/>
    </graphics>
    <sound model='ich6'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </sound>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='3'/>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='4'/>
    </redirdev>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </memballoon>
  </devices>
</domain>
```

Then I booted and Windows wanted to reboot. After that, I  opened the device manager and updated drivers *off the root folder of the CD-ROM*.

![screenshot from 2018-02-20 18-08-12](https://user-images.githubusercontent.com/322807/36438317-d720ba98-1669-11e8-96b8-20347380c943.png)

First it installed this driver:

![screenshot from 2018-02-20 18-08-22](https://user-images.githubusercontent.com/322807/36438336-e59133d2-1669-11e8-9065-89b37522d53b.png)


but that didn't seem to have worked:

![screenshot from 2018-02-20 18-08-31](https://user-images.githubusercontent.com/322807/36438355-f67af818-1669-11e8-8d69-63a227791e27.png)


After installing the other drivers *off the root directory of the CD-ROM*, I tried again to update the VGA graphics adapter driver. This time it selected this driver:

![screenshot from 2018-02-20 18-11-29](https://user-images.githubusercontent.com/322807/36438417-2f137632-166a-11e8-85fa-054fa9c31f83.png)

Instead of rebooting as it requested I opened the driver details:

![screenshot from 2018-02-20 18-11-49](https://user-images.githubusercontent.com/322807/36438426-3413a6de-166a-11e8-9433-2e0ba96ff2a5.png)

After a reboot, the machine crashed:

![screenshot from 2018-02-20 18-17-17](https://user-images.githubusercontent.com/322807/36438485-606c3228-166a-11e8-9d91-1edd79da919a.png)


I hope that this allows you to reproduce this issue.

**Comment by sameehj** [comment] 2018-03-12 12:52
Hi @muelli,
Thank you for this very detailed bug report, we will soon try to reproduce and update you with our findings :)

**Comment by sameehj** [comment] 2018-03-24 11:06
Update:
We were able to successfully reproduce the issue and know how to fix it. We'll be sending patches to the spice mailing list as the qxl driver is a sub-component of spice.

**Comment by sameehj** [comment] 2018-04-23 10:05
The commit that fixes the issue is now in upstream, so this issue should be fixed in the next release.
Commit:
https://gitlab.com/spice/qxl-wddm-dod/commit/9b0bc8188366c3eebe1519fa1e153e51ebcdf16b

I am closing the issue, please reopen in case you think the issue is not fully resolved.
Thanks for reporting this :)

**Closed by sameehj** 2018-04-23 10:05 UTC
