### ISSUE TITLE
Citrix Workspaces not compatible with QXL DOD

### ISSUE THREAD

**Issue by vic-t** [virtio-win/kvm-guest-drivers-windows#368] opened 2019-01-25 11:44 UTC
There is an incompatibility between the "Citrix Indirect Display Adapter" installed by Citrix Workspaces for Windows version 1812 (originally Citrix Receiver) and the QXL DOD adapter driver for Windows 10. 

To reproduce: 

- Run VM with Windows 10 build 1803
- Relevant VM config: Video QXL, Display Spice, USB Tablet device
- Install Spice Guest Tools (stable or latest)
- Install Citrix Workspaces 1812 (https://www.citrix.de/downloads/workspace-app/windows/workspace-app-for-windows-latest.html)
- Reboot VM

==> After reboot, host mouse and automatic resolution adjustment no longer work. Reinstalling Spice tools has no effect. 

Solution: 

Open device manager, delete "Citrix Indirect Display Adapter", reboot VM.

**Comment by YanVugenfirer** [comment] 2019-01-27 09:53
I guess the reason is that Citril driver overrides those settings. Worth a quick look, but not sure we can do something about it from our side.

**Comment by jsamuel1** [comment] 2019-06-02 23:48
I had been struggling with this for a while - Can this be documented as a known issue for other Citrix Workspaces users to understand the limitation, if not fixable?

**Comment by 9strands** [comment] 2019-08-30 00:53
I can confirm that this is still an issue currently with latest release of RHEL drivers installed in the guest Win10 vm

**Comment by rmerren** [comment] 2019-11-08 17:03
Thanks for this...I was able to get the mouse pointer working again by removing that driver. When uninstalling the device be sure to check the box that asks if you want to delete the driver file--otherwise it reinstalls itself when you reboot.

**Comment by tuxillo** [comment] 2020-02-26 12:01
Thanks for this. Please this should be documented somewhere, the issue is still relevant!

**Comment by misiektw** [comment] 2020-03-13 15:26
I dont think this is Citrix IDA specific, or even QXL. I just added physical passtrough GPU to QXL enabled Win10 VM and my mouse is gone too. Not just invisible, gone, no input at all. Even if I turn off GPU in windows and leave only QXL enabled. Once i switch to VGA, mouse works.

However, if I stop SPICE VDAgent service (vdservice.exe), mouse is back even with QXL driver.

**Comment by willberriss** [comment] 2020-04-02 14:23
Mine used to work for a few tens of minutes or even hours and then disappear suddenly and I would have to move my mouse to the top of the screen (invisibly, so I had to guess) and then click somewhere up the top of the screen it would come back again.  I just lived with it for about a year. Since upgrading my kvm host from Debian 9 to Debian 10 the other day, I've found that when my mouse disappears now nothing will get it back. So I've just disabled and removed the Citrix driver today and all is good so far (I'm about 3 hours in.)  Thank you so much for finding this bug/solution. :)

**Comment by willberriss** [comment] 2020-04-03 05:59
> I dont think this is Citrix IDA specific, or even QXL. 

I think you are right.  This morning my disappearing mouse cursor issue came back again, despite that Citrix driver not being present.  I found I could get it back it if I removed hardware using kvm console - i.e. remove the EvTouch USB Graphics Tablet for the Windows10 VM.  When I did that I got my mouse back.  But then I found I could not get out of the Winsdows10 VM: placing my cursor at the top middle of the screen did not make the little VM drop down window appear.  I was stuck in my Windows 10 VM.  I noticed too that the touch pad pen still had some activity in it, despite being removed.  Anyway I had to shutdown the VM to get out of it.  And I found I had to add hardware -> EvTouch USB Graphics Tablet in kvm console for this Windows10 VM in order for the kvm centre-middle drop down window to appear, so it seems I have no choice, other than to completely unplug my Wacom tablet perhaps.  So I will just have to live with the intermittent issue, but at least I have some things to try to get the mouse back when it goes awol. :-/

**Comment by peterhoeg** [comment] 2020-05-29 08:02
Uninstalling citrix definitely solves this. And I did not have the problems (no mouse and no auto-resize of the resolution) before installing citrix.

**Comment by supercheetah** [comment] 2020-06-01 15:18
I just installed a newer version (after uninstalling the old one, of course) of Citrix Workspace, 2020, and it doesn't seem to have this problem any more.  I'm not exactly sure what was wrong with the old version, but this seems to be resolved with this newer version.  I tried looking through the WinEvents with the old version to figure this out, but couldn't.  Do we want to close this with just install the latest version of Citrix Workspace?

**Comment by misiektw** [comment] 2020-06-02 10:29
> After I had reinstalled it, and tried changing one of the windows to full screen, I noticed that it didn't dynamically change the resolution of the virtual monitor like it normally does.

Probably SPICE VDAgent service wasn't working for a while. Try to manually stop/start it, you will see that mouse works and then it doesn't.

If your mouse is just invisible then, like willberriss found out earlier, messing with EVTouch can fix things (i removed it from one of my VMs and its working). Also enabling cursor shadow in mouse settings works in some cases (but bit annoying even in lowest delay).

However when mouse is gone completely (not just invisible), like with my second GPU passtrough VM (no Citrix at all), then only stopping SPICE VDAgent restores it. So my workaround is to disable VDAgent Service and use f.e. Barrier to get copy/paste back.

I wasn't messing with this lately, because workarounds kinda work. However, I'm pretty positive that root of this problem isn't Citrix specific at all. It seems any software adding some kind additional graphic driver (in my case its NVidia, for passtrough) is causing QXL or Spice VDAgent to malfunction.

**Comment by devaux** [comment] 2020-07-09 10:55
Can confirm this: No mouse after installing Citrix Workspace 2006.1 (Jun.5).
Removing Citrix Workspace OR Spice Agent "solved" this problem.

**Comment by nkichukov** [comment] 2020-08-27 10:58
I was also able to workaround the problem by opening device manager and disabling "Citrix Indirect Display Adapter".

**Comment by Jaydoff** [comment] 2020-09-28 09:51
I'm still having this issue 09/2020, occurred after I installed new citrix workspace 2009 20.9.0.3, at first i only removed "Citrix Indirect Display Adapter" and when i restarted it installed itself back. So I had to connect to my win 10 VM using Video VGA display on virt-manager, then once in win 10 ->  device manage -> display adapter -> right click disable , shutdown change the Video back to QXL and viola it rebooting and my mouse cusor was back :)

**Comment by nabice** [comment] 2020-11-05 10:12
I also have this problem, I did not install Citrix Workspace, but no mouse, no resolution adjustment.

**Comment by WarShoe** [comment] 2020-11-11 18:23
I installed kvm with  windows10 guest OS yesterday. In general the results are quite good. Webcam+Sound+mic works (I am able to use skype from windows). Citrix Workspace 20.10.0.20 also works. There is only one problem: I cannot use the native  screen resolution 3440x1440 of my display. The settings I use now is 2560x1440. I am aware of the "memory problem", the memory limit has been increased:
`
  <model type="virtio" vram="65536" heads="1" primary="yes">
    <resolution x="3440" y="1440"/>
  </model>
`
But without any effect. Do I need to add some special parameters?

If I switch to QXL mode, I do have a wider choice of high resolutions, but again 3440x1440 line is missing. And yes, there is no mouse with QXL. So basically this mode is useless.

**Comment by pcfe** [comment] 2020-11-12 10:32
> I was also able to workaround the problem by opening device manager and disabling "Citrix Indirect Display Adapter".

Thank you very much for that hint. This fixes the breakage that Citrix introduced yet still allows me to use the Citrix client.

So far this fix (disable but do not uninstall) survived one reboot of the VM (fingers crossed it stays fixed), while when I completely removed the crappy  "Citrix Indirect Display Adapter" it got re-added ion the next boot and Citrix broke my VM again.

**Comment by jensbin** [comment] 2020-12-12 15:25
I came across this https://forum.unity.com/threads/unity-2018-2-7f1-windows-standalone-crash-on-first-run-unityplayer-dll-caused-an-access-violation.556585/#post-3935722

Install Citrix WorkspaceApp without Citrix Casting:
`CitrixWorkspaceApp.exe ADDLOCAL=ReceiverInside,ICA_Client,AM,SELFSERVICE,DesktopViewer,Flash,Vd3d,WebHelper,BrowserEngine`

For me it is not adding the 'Citrix Indirect Display Adapter'.

**Comment by YanVugenfirer** [comment] 2020-12-13 14:12
The fix should be in vdagent: https://gitlab.freedesktop.org/spice/win32/vd_agent/-/commit/65e8edcf974651fba686021384f0547c463a5653

**Comment by nkichukov** [comment] 2020-12-14 09:20
Thanks for the fix, when can we see a binary package that will include this fix, ie a new release for windows?

**Comment by YanVugenfirer** [comment] 2020-12-14 10:28
Unfortunately, I don't know. I suggest asking on spice-devel list. https://lists.freedesktop.org/mailman/listinfo/spice-devel

**Comment by nkichukov** [comment] 2020-12-14 10:54
https://lists.freedesktop.org/archives/spice-devel/2020-December/052099.html

**Comment by hect1995** [comment] 2020-12-18 08:04
> Unfortunately, I don't know. I suggest asking on spice-devel list. https://lists.freedesktop.org/mailman/listinfo/spice-devel

Sorry for the silly question but what am I supposed to change to use your workaround? I mean do I have to add those lines of code? Where?

**Comment by nishihatapalmer** [comment] 2021-01-22 23:39
I have also had the disappearing mouse with a Win 10 guest.  Uninstalling Citrix has fixed the problem for me too, awaiting the main fix to spice so I can use Citrix again.

**Comment by Houiin** [comment] 2021-02-07 15:31
> I dont think this is Citrix IDA specific, or even QXL. I just added physical passtrough GPU to QXL enabled Win10 VM and my mouse is gone too. Not just invisible, gone, no input at all. Even if I turn off GPU in windows and leave only QXL enabled. Once i switch to VGA, mouse works.
> 
> However, if I stop SPICE VDAgent service (vdservice.exe), mouse is back even with QXL driver.

same problem.....How do you solve it ?

**Comment by misiektw** [comment] 2021-02-07 19:50
> same problem.....How do you solve it ?

Like I said. "Stop SPICE VDAgent service"... You loose clipboard, but you can use Barrier or Synergy, for example, to get it back.

**Comment by ericzolf** [comment] 2021-03-15 07:52
A colleague pointed me to this issue, which solved my life. Few comments:
* the issue appears for me only after each reboot. If I uninstall Citrix, the mouse comes back, and stays if I reinstall it, until the next reboot. That was my workaround until the dear colleague pointed me here.
* quick fix was after this discovery to disable the Citrix indirect driver (without mouse: Windows-key, search for device, open the Device Manager, then tab etc: 
![image](https://user-images.githubusercontent.com/3105685/111119889-f9dd7580-856a-11eb-8a78-9d58b08e6b95.png)
* long-term fix seems to simply change the video driver from QXL to Virtio in virt-manager; after re-enabling the Citrix driver, it at least survived one reboot and one shutdown + run. I guess the solution requires to have the Virtio drivers installed _before_ switching.
![image](https://user-images.githubusercontent.com/3105685/111120407-9738a980-856b-11eb-9de3-1f35d44ec4bc.png)
So, all good for now...

**Comment by Cytomax55** [comment] 2021-04-30 14:43
Any updates with this... This is the only reason I'm using virtual box instead of kvm

**Comment by Narinas** [comment] 2021-09-20 15:41
Thanks a lot, exactly my issue and resolution.

**Comment by MichaelHeimann** [comment] 2021-10-01 12:23
Hi,
Since I don't have Admin rights in a Corporate VM environment I cannot uninstall the Citrix Adapter (what is it used for?) but work with the Virtio driver.

Is there any plan to fix the incompatibility with the Citrix Adapter?

Cheers,
Michael

**Comment by ybendito** [comment] 2021-10-03 13:26
Hi people. Sorry for saying it but this discussion has no relation to virtio-win drivers at all.
As was pointed above by Yan, the fix is in upstream of https://gitlab.freedesktop.org/spice/win32/vd_agent
Clone this repository (do not fork it, as it has submodules, probably with relative path) and build it on Linux using mingw64, this will produce Windows x64 binaries. There is also Wix script that can be used to create an installer.
You may prefer to wait until the ready-to-use binaries appear on spice-space.org, but we have no idea when this may happen as this is not related to virtio-win. Opening an issue under https://gitlab.freedesktop.org/spice/win32/vd_agent will not make things worse, as well as mailing to spice-devel@lists.freedesktop.org.

**Closed** 2022-01-17 14:03 UTC
Labels: Not virtio-win, Spice

**Comment by jmcisvt** [comment] 2023-02-09 01:28
Uninstalling Citrix fixed my VM mouse issue.
