### ISSUE TITLE
howto set viorng as default?

### ISSUE THREAD

**Issue by rgl** [virtio-win/kvm-guest-drivers-windows#393] opened 2019-04-30 19:09 UTC
How do we set `viorng` as the default cng/bcrypt provider? Why isn't it the default?

I've tried to reorder the providers listed at `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Cryptography\Configuration\Local\Default\00000006\RNG\Providers` to:

```
QEMU VirtIO RNG Provider
Microsoft Primitive Provider
```

but a while after booting windows shows the following error and restarts :-(

![image](https://user-images.githubusercontent.com/43356/56986148-ecd75900-6b81-11e9-9cb7-89ab2affea48.png)

How do we prove that the default is `viorng`? Currently, I'm doing an example at https://github.com/rgl/list-cng-rng-providers I'm assuming the default is the first provider that is displayed, is it really like that?

Event viewer had a crash on `lsass.exe`, and you can see that `viorngum.dll` is also loaded:

```
Version=1
EventType=CriticalProcessFault2
EventTime=132011239137275018
ReportType=2
Consent=1
UploadTime=132011251616879419
ReportStatus=2147487744
ReportIdentifier=2cc7785b-2f54-40ca-b476-d42f680495c2
IntegratorReportIdentifier=c53d1ca7-7259-46a2-a5d9-136c04497f8d
Wow64Host=34404
NsAppName=lsass.exe
OriginalFilename=lsass.exe
AppSessionGuid=00000244-0000-000c-0b12-ef8485ffd401
TargetAppId=W:0000f519feec486de87ed73cb92d3cac802400000000!00000fb26350106c9bdd196d4e7d01eb30007663687c!lsass.exe
TargetAppVer=2098//07//10:04:45:46!ed7d!lsass.exe
BootId=4294967295
TargetAsId=12
IsFatal=1
EtwNonCollectReason=4
Response.BucketId=85c729a9e978ec5da69c23ca516086c3
Response.BucketTable=5
Response.LegacyBucketId=1629216517056923331
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=lsass.exe
Sig[1].Name=Application Version
Sig[1].Value=10.0.17763.1
Sig[2].Name=Application Timestamp
Sig[2].Value=f1beaffa
Sig[3].Name=Fault Module Name
Sig[3].Value=StackHash_76a1
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=00000000
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=PCH_74
Sig[8].Name=Exception Data
Sig[8].Value=00000000
Sig[9].Name=Exception Flags
Sig[9].Value=0x00000000
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.17763.2.0.0.272.79
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=2070
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=76a1
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=76a173c26a6dc2e3cd83ac8fd9f8bdb9
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=7b3f
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=7b3f634c955ac91fe3f1e745337a968a
UI[2]=C:\Windows\system32\lsass.exe
UI[5]=Check online for a solution (recommended)
UI[6]=Check for a solution later (recommended)
UI[7]=Close
UI[8]=Local Security Authority Process stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=C:\Windows\system32\lsass.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\System32\RPCRT4.dll
LoadedModule[5]=C:\Windows\system32\lsasrv.dll
LoadedModule[6]=C:\Windows\System32\msvcrt.dll
LoadedModule[7]=C:\Windows\System32\WS2_32.dll
LoadedModule[8]=C:\Windows\system32\SspiCli.dll
LoadedModule[9]=C:\Windows\System32\sechost.dll
LoadedModule[10]=C:\Windows\System32\WLDAP32.dll
LoadedModule[11]=C:\Windows\System32\ucrtbase.dll
LoadedModule[12]=C:\Windows\System32\MSASN1.dll
LoadedModule[13]=C:\Windows\SYSTEM32\samsrv.dll
LoadedModule[14]=C:\Windows\System32\bcrypt.dll
LoadedModule[15]=C:\Windows\System32\CRYPT32.dll
LoadedModule[16]=C:\Windows\system32\ncrypt.dll
LoadedModule[17]=C:\Windows\system32\NTASN1.dll
LoadedModule[18]=C:\Windows\system32\Wldp.dll
LoadedModule[19]=C:\Windows\System32\combase.dll
LoadedModule[20]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[21]=C:\Windows\System32\WINTRUST.dll
LoadedModule[22]=C:\Windows\system32\msprivs.DLL
LoadedModule[23]=C:\Windows\SYSTEM32\netprovfw.dll
LoadedModule[24]=C:\Windows\system32\JOINUTIL.DLL
LoadedModule[25]=C:\Windows\system32\negoexts.DLL
LoadedModule[26]=C:\Windows\System32\CRYPTSP.dll
LoadedModule[27]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[28]=C:\Windows\system32\kerberos.DLL
LoadedModule[29]=C:\Windows\system32\KerbClientShared.dll
LoadedModule[30]=C:\Windows\system32\cryptdll.dll
LoadedModule[31]=C:\Windows\system32\mswsock.dll
LoadedModule[32]=C:\Windows\system32\msv1_0.DLL
LoadedModule[33]=C:\Windows\system32\NtlmShared.dll
LoadedModule[34]=C:\Windows\system32\netlogon.DLL
LoadedModule[35]=C:\Windows\System32\powrprof.dll
LoadedModule[36]=C:\Windows\System32\advapi32.dll
LoadedModule[37]=C:\Windows\system32\USERENV.dll
LoadedModule[38]=C:\Windows\system32\gmsaclient.dll
LoadedModule[39]=C:\Windows\System32\profapi.dll
LoadedModule[40]=C:\Windows\system32\netutils.dll
LoadedModule[41]=C:\Windows\system32\DNSAPI.dll
LoadedModule[42]=C:\Windows\System32\NSI.dll
LoadedModule[43]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[44]=C:\Windows\system32\tspkg.DLL
LoadedModule[45]=C:\Windows\system32\pku2u.DLL
LoadedModule[46]=C:\Windows\system32\cloudAP.DLL
LoadedModule[47]=C:\Windows\SYSTEM32\MicrosoftAccountCloudAP.dll
LoadedModule[48]=C:\Windows\SYSTEM32\DPAPI.DLL
LoadedModule[49]=C:\Windows\system32\rsaenh.dll
LoadedModule[50]=C:\Windows\system32\wdigest.DLL
LoadedModule[51]=C:\Windows\system32\schannel.DLL
LoadedModule[52]=C:\Windows\system32\viorngum.dll
LoadedModule[53]=C:\Windows\System32\SETUPAPI.dll
LoadedModule[54]=C:\Windows\System32\cfgmgr32.dll
LoadedModule[55]=C:\Windows\system32\DEVOBJ.dll
LoadedModule[56]=C:\Windows\system32\efslsaext.dll
LoadedModule[57]=C:\Windows\System32\shcore.dll
LoadedModule[58]=C:\Windows\system32\dpapisrv.dll
LoadedModule[59]=C:\Windows\SYSTEM32\SspiSrv.dll
LoadedModule[60]=C:\Windows\system32\KDCPW.DLL
LoadedModule[61]=C:\Windows\system32\rassfm.DLL
LoadedModule[62]=C:\Windows\system32\scecli.DLL
LoadedModule[63]=C:\Windows\SYSTEM32\winsta.dll
LoadedModule[64]=C:\Windows\SYSTEM32\wevtapi.dll
LoadedModule[65]=C:\Windows\System32\msvcp_win.dll
LoadedModule[66]=C:\Windows\system32\keyiso.dll
LoadedModule[67]=C:\Windows\system32\NCRYPTPROV.DLL
LoadedModule[68]=C:\Windows\System32\ngcpopkeysrv.dll
LoadedModule[69]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[70]=C:\Windows\system32\PCPKsp.dll
LoadedModule[71]=C:\Windows\SYSTEM32\ntmarta.dll
LoadedModule[72]=C:\Windows\system32\tbs.dll
LoadedModule[73]=C:\Windows\System32\imagehlp.dll
LoadedModule[74]=C:\Windows\system32\ncryptsslp.dll
LoadedModule[75]=C:\Windows\system32\dssenh.dll
LoadedModule[76]=C:\Windows\SYSTEM32\gpapi.dll
LoadedModule[77]=C:\Windows\SYSTEM32\mskeyprotect.dll
LoadedModule[78]=C:\Windows\System32\SecureTimeAggregator.dll
LoadedModule[79]=C:\Windows\system32\DSROLE.dll
LoadedModule[80]=C:\Windows\System32\cryptnet.dll
LoadedModule[81]=C:\Windows\System32\kernel.appcore.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=17763
OsInfo[3].Key=ubr
OsInfo[3].Value=437
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=79
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=272
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=3
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=435
OsInfo[15].Key=osinsty
OsInfo[15].Value=2
OsInfo[16].Key=iever
OsInfo[16].Value=11.437.17763.0-11.0.120
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=4096
OsInfo[19].Key=svolsz
OsInfo[19].Value=59
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=180914
OsInfo[22].Key=bldtm
OsInfo[22].Value=1434
OsInfo[23].Key=bldbrch
OsInfo[23].Value=rs5_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.17763.437.amd64fre.rs5_release.180914-1434
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=ServerStandardEval
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Stopped working
ConsentKey=CriticalProcessFault2
AppName=Local Security Authority Process
AppPath=C:\Windows\system32\lsass.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=4CEB14BEB5381DB1F8AA51D2248C3393
MetadataHash=43086228
```

**Comment by hammerg** [comment] 2019-05-12 05:43
Hi,

I'm not sure. I never tried to set the default RNG provider and always choose it manually on my tests.

Do you have the memory.dmp file of the crash that you had? I would like to see if it caused by the virtio-rng driver or not.

Thanks, Gal.

**Comment by rgl** [comment] 2019-05-12 10:50
I'm sorry, but I was not able to reproduce this today...

BTW, do you known why virtio RNG provider is not set as default?

**Comment by rgl** [comment] 2019-05-12 11:01
Oh it crashed after all... the following dumps were created with `procdump -mp -i c:\dumps`:

[lsass-dump.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/3169983/lsass-dump.zip)

Maybe this is because I'm using `/dev/random` instead of `/dev/urandom`? Because `random` blocks and something times out?

BTW, do you known why virtio RNG provider is not set as default?

**Comment by hammerg** [comment] 2019-05-14 06:18
> Oh it crashed after all... the following dumps were created with `procdump -mp -i c:\dumps`:
> 
> [lsass-dump.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/3169983/lsass-dump.zip)

This looks like a service crash rather than a driver crash. After the crash, do you have a C:\Windows\MEMORY.DMP file or dump files in C:\Windows\Minidump directory?
 
> Maybe this is because I'm using `/dev/random` instead of `/dev/urandom`? Because `random` blocks and something times out?

No. It is probably crashed because you did changes to the registry. The entropy source should not affect the driver behavior.
 
> BTW, do you known why virtio RNG provider is not set as default?

Like I wrote before. As far as I know, there is no default RNG provider in Windows. Feel free to prove me wrong.

**Comment by rgl** [comment] 2019-05-14 20:12
> > Oh it crashed after all... the following dumps were created with `procdump -mp -i c:\dumps`:
> > [lsass-dump.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/3169983/lsass-dump.zip)
> 
> This looks like a service crash rather than a driver crash. After the crash, do you have a C:\Windows\MEMORY.DMP file or dump files in C:\Windows\Minidump directory?

Nope. Do I need to configure anything to have them generated?

Are those created when there's a kernel/driver crash?

Does procdump interfere with the creation of those?

> > Maybe this is because I'm using `/dev/random` instead of `/dev/urandom`? Because `random` blocks and something times out?
> 
> No. It is probably crashed because you did changes to the registry. The entropy source should not affect the driver behavior.

I've changed it to `/dev/urandom`, moved the qemu provider to the first list position, and the crashes do not happen anymore.

> > BTW, do you known why virtio RNG provider is not set as default?
> 
> Like I wrote before. As far as I know, there is no default RNG provider in Windows. Feel free to prove me wrong.

From the Win32 API side of things, it seems to be a default/system-preferred, e.g.: from https://github.com/rgl/list-cng-rng-providers/blob/master/main.c#L152-L158:

```c
status = BCryptGenRandom(
        NULL,                           // hAlgorithm
        buffer,                         // pbBuffer
        sizeof(buffer),                 // cbBuffer
        BCRYPT_USE_SYSTEM_PREFERRED_RNG // dwFlags
    );
```



When I'm using `/dev/random` on qemu that call takes a long time to return, so it seems its really calling into qemu, hence the `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Cryptography\Configuration\Local\Default\00000006\RNG\Providers` registry key that I've mentioned originally seems to be changing that default.

**Comment by hammerg** [comment] 2019-05-19 12:23
> > > Oh it crashed after all... the following dumps were created with `procdump -mp -i c:\dumps`:
> > > [lsass-dump.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/3169983/lsass-dump.zip)
> > 
> > 
> > This looks like a service crash rather than a driver crash. After the crash, do you have a C:\Windows\MEMORY.DMP file or dump files in C:\Windows\Minidump directory?
> 
> Nope. Do I need to configure anything to have them generated?

This PC >> Properties >> Advanced system setting >> Startup and Recovery >> System failure

Write debugging information should be at least "Small memory dump".
 
> Are those created when there's a kernel/driver crash?

Yep.
 
> Does procdump interfere with the creation of those?

I don't think it can do it. But I'm not familiar with this tool.

> > > Maybe this is because I'm using `/dev/random` instead of `/dev/urandom`? Because `random` blocks and something times out?
> > 
> > 
> > No. It is probably crashed because you did changes to the registry. The entropy source should not affect the driver behavior.
> 
> I've changed it to `/dev/urandom`, moved the qemu provider to the first list position, and the crashes do not happen anymore.
> 

After it worked with "/dev/urandom". Did you try again to see if it still crash with "/dev/random"? This check will roll out a crash due to registry changes.

> > > BTW, do you known why virtio RNG provider is not set as default?
> > 
> > 
> > Like I wrote before. As far as I know, there is no default RNG provider in Windows. Feel free to prove me wrong.
> 
> From the Win32 API side of things, it seems to be a default/system-preferred, e.g.: from https://github.com/rgl/list-cng-rng-providers/blob/master/main.c#L152-L158:
> 
> ```c
> status = BCryptGenRandom(
>         NULL,                           // hAlgorithm
>         buffer,                         // pbBuffer
>         sizeof(buffer),                 // cbBuffer
>         BCRYPT_USE_SYSTEM_PREFERRED_RNG // dwFlags
>     );
> ```
> 
> When I'm using `/dev/random` on qemu that call takes a long time to return, so it seems its really calling into qemu, hence the `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Cryptography\Configuration\Local\Default\00000006\RNG\Providers` registry key that I've mentioned originally seems to be changing that default.

This not not really changing the default provider. This is more like an option for the application developer to skip selecting the RNG provider by himself. It is not like in Linux, where you can add virtio-rng to the RNG providers and then every application that reads from /dev/random get its RNG from outside the guest.

**Comment by rgl** [comment] 2019-05-20 21:33
> > > > Oh it crashed after all... the following dumps were created with `procdump -mp -i c:\dumps`:
> > > > [lsass-dump.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/3169983/lsass-dump.zip)
> > > 
> > > 
> > > This looks like a service crash rather than a driver crash. After the crash, do you have a C:\Windows\MEMORY.DMP file or dump files in C:\Windows\Minidump directory?
> > 
> > 
> > Nope. Do I need to configure anything to have them generated?
> 
> This PC >> Properties >> Advanced system setting >> Startup and Recovery >> System failure
> 
> Write debugging information should be at least "Small memory dump".

Its using the [default "Automatic memory dump"](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/automatic-memory-dump) which is above "Small memory dump".


> > I've changed it to `/dev/urandom`, moved the qemu provider to the first list position, and the crashes do not happen anymore.
> 
> After it worked with "/dev/urandom". Did you try again to see if it still crash with "/dev/random"?

I did, and it still crashed. I did those back-and-forward a couple of times. Always the same result.


> This check will roll out a crash due to registry changes.

What do you mean by this?


> > > > BTW, do you known why virtio RNG provider is not set as default?
> > > 
> > > 
> > > Like I wrote before. As far as I know, there is no default RNG provider in Windows. Feel free to prove me wrong.
> > 
> > 
> > From the Win32 API side of things, it seems to be a default/system-preferred, e.g.: from https://github.com/rgl/list-cng-rng-providers/blob/master/main.c#L152-L158:
> > ```c
> > status = BCryptGenRandom(
> >         NULL,                           // hAlgorithm
> >         buffer,                         // pbBuffer
> >         sizeof(buffer),                 // cbBuffer
> >         BCRYPT_USE_SYSTEM_PREFERRED_RNG // dwFlags
> >     );
> > ```
> > 
> > 
> > When I'm using `/dev/random` on qemu that call takes a long time to return, so it seems its really calling into qemu, hence the `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Cryptography\Configuration\Local\Default\00000006\RNG\Providers` registry key that I've mentioned originally seems to be changing that default.
> 
> This not not really changing the default provider. This is more like an option for the application developer to skip selecting the RNG provider by himself. It is not like in Linux, where you can add virtio-rng to the RNG providers and then every application that reads from /dev/random get its RNG from outside the guest.

IMHO its more-or-less the same thing. I would guess that most developers are just using `BCRYPT_USE_SYSTEM_PREFERRED_RNG` (e.g. alike the [std .net library](https://github.com/dotnet/corefx/search?q=BCryptGenRandom&unscoped_q=BCryptGenRandom), which doesn't even give you an option to change the value).

**Comment by ybendito** [comment] 2019-12-26 02:36
@hammerg Probably we can close the issue. I also do not see how can we set virtio-rng to be preferred provider. A test code for virtio-rng added https://github.com/virtio-win/kvm-guest-drivers-windows/tree/master/viorng/test

**Comment by ybendito** [comment] 2020-02-25 12:33
Closing the issue, please reopen if needed

**Closed by ybendito** 2020-02-25 12:33 UTC
