### ISSUE TITLE
virtio-stor:different virtio disks in windows have same unique id

### ISSUE THREAD

**Issue by zhouwjfi** [virtio-win/kvm-guest-drivers-windows#353] opened 2018-12-07 09:32 UTC
Hi yan,

Recently, I meet a bug with unique id in windows.

In some windows versions such as windows 2012, windows 2016, we can get disk's unique id by `get-disk -Number 1 | fl * | findstr UniqueId`. Some apps depend it. 

But each virtio disk shares the same value: 0x3141463431303031.
 I found the reason is virtio-stor driver write it to 0x83 vpd page, and got patches related with the issue: c766f2653, a3c3325, 8ee31bf .Unfortunately, the latest code just change the behavior in windows 10 and later.Should we optimize it in the older versions?

Thanks
Zhou

**Comment by YanVugenfirer** [comment] 2018-12-07 10:04
Adding Vadim to the thread.

Hi Zhou,

Do you have a patch proposal?
I also added Vadim to the thread to look at it.

Best regards,
Yan.

**Comment by vrozenfe** [comment] 2018-12-08 05:48
Why not to give unique serial number to each virtio-blk drive then?
Could you please let me know which apps exactly relied on information obtained through VPD VPD_DEVICE_IDENTIFIERS (0x83) rather that VPD_SERIAL_NUMBER (0x80) ?

Thanks,
Vadim.

**Comment by zhouwjfi** [comment] 2018-12-08 08:35
Hi Vadim,

As I know, server manger in windows 2012 use it.
When we reset one disk in server manager, another disk may be reset, if there are more than one virtio disk.

Thanks
Zhou

**Comment by zhouwjfi** [comment] 2018-12-08 08:47
Hi Yan,

I'm not familiar with windows drivers and vpd, not sure if the following change is good.
I just set the Identifier with the bus and slot numbers. And it works good when installing win2008 and reset disk in win2016.

        IdentificationDescr->Identifier[0] = (adaptExt->system_io_bus_number >> 12) & 0xF;
        IdentificationDescr->Identifier[1] = (adaptExt->system_io_bus_number >> 8) & 0xF;
        IdentificationDescr->Identifier[2] = (adaptExt->system_io_bus_number >> 4) & 0xF;
        IdentificationDescr->Identifier[3] = adaptExt->system_io_bus_number & 0xF;
        IdentificationDescr->Identifier[4] = (adaptExt->slot_number >> 12) & 0xF;
        IdentificationDescr->Identifier[5] = (adaptExt->slot_number >> 8) & 0xF;
        IdentificationDescr->Identifier[6] = (adaptExt->slot_number >> 4) & 0xF;
        IdentificationDescr->Identifier[7] = adaptExt->slot_number & 0xF;

Thanks
Zhou

> Adding Vadim to the thread. Hi Zhou, Do you have a patch proposal? I also added Vadim to the thread to look at it. Best regards, Yan.
> […](#)
> On Dec 7, 2018, at 11:32, zhouwjfi ***@***.***> wrote: Hi yan, Recently, I meet a bug with unique id in windows. In some windows versions such as windows 2012, windows 2016, we can get disk's unique id by get-disk -Number 1 | fl * | findstr UniqueId. Some apps depend it. But each virtio disk shares the same value: 0x3141463431303031. I found the reason is virtio-stor driver write it to 0x83 vpd page, and got patches related with the issue: [c766f26](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/c766f265343c1983c4eab272408e79090c26a0a0), [a3c3325](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/a3c3325e3be950b7100d7a47e20ea02194e4c9f5), [8ee31bf](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/8ee31bf0ad7c9835ba72b6d08e7502523b59e79b) .Unfortunately, the latest code just change the behavior in windows 10 and later.Should we optimize it in the older versions? Thanks Zhou — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by vrozenfe** [comment] 2018-12-08 09:03
Thanks a lot.

I would like to know the exact scenario how to reproduce the problems.
Is the problems reproducible is you specify a drive serial name exlpicitly? 

Best regards,
Vadim.

**Comment by vrozenfe** [comment] 2018-12-08 09:05
Sorry closed it by mistake. Please reopen it again to trace this issue in the future.

**Comment by zhouwjfi** [comment] 2018-12-09 01:07
> Thanks a lot.
> 
> I would like to know the exact scenario how to reproduce the problems.
> Is the problems reproducible is you specify a drive serial name exlpicitly?
> 
> Best regards,
> Vadim.

I tried to specify different serial numbers and it didn't help.

Thanks
Zhou

**Comment by vrozenfe** [comment] 2018-12-09 13:09
I see.
Then please help me to understand and reproduce the scenario when you meet the problem.
Is it a kind of direct LUN storage or SAN storage have been involved? Do you see the problem during Windows Install phase or/and any other time after that? 
Don't get me wrong, but in my understanding , for pre-Win10 platforms page 0x83 is not a must for regular SCSI adapters. So, to fix the problem properly we need to know how to reproduce it.
Because we might need to use the same mechanism as implemented in
#if (NTDDI_VERSION >= NTDDI_WIN10)
...
#else 
branch - if possible, report serial number (which we can keep more or less persistent) first, rather than vendor id extended with slot id (which can be changed between VM restarts).

Best,
Vadim.

**Comment by zhouwjfi** [comment] 2018-12-10 01:58
OK, I will show you detailed steps to reproduce it.
vm os: Windows Server 2012 R2 Datacenter
disks:
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none' io='native'/>
      <source file='/root/test1.img'/>
      <target dev='vdb' bus='virtio'/>
      <serial>zwj-test1</serial>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </disk> 
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none' io='native'/>
      <source file='/root/test2.img'/>
      <target dev='vdc' bus='virtio'/>
      <serial>zwj-test2</serial>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </disk>
steps:
1. install vm and virtio driver
2. start vm and initialize the two virtio disks
3. enter Server Manager -> File and Storage Services -> disks, then you can see the two virtio disks
4. right click on one disk and choose 'Reset Disk'
5. right click on another disk and choose 'Reset disk'. Then, you will get a error message:
    'Failed to reset disk - The disk has not been initialized'

-- reproduce steps end --

I guess Bug 1566298 is caused by the vpd page can't be decoded.
When I use sg3_utils to query the 0x83 page, it shows only data with 8, 12, 16 length can be decoded.
I mean we can report serial number first but  maybe we should adjust the length.

About slot id, though it may change, it haven't shown any side effects. At least, it can solve these bugs we have met. So it is an alternative choice.

Thanks
Zhou

**Comment by vrozenfe** [comment] 2018-12-11 04:46
Thanks a lot.
The patch looks good to me. Just give me a couple of days to do some quick testing before giving it 
approval.

Best regards,
Vadim.

**Comment by vrozenfe** [comment] 2018-12-17 03:07
Hi Zhou,

Could you please create a pull request to approve and merge your changes?

Thanks,
Vadim.

**Comment by zhouwjfi** [comment] 2018-12-17 06:54
Done. Pull request #358 is created.

Thanks
Zhou

**Closed** 2018-12-18 01:32 UTC
