### ISSUE TITLE
Virtio-FS on Windows issues renaming files and folders

### ISSUE THREAD

**Issue by surfchris** [virtio-win/kvm-guest-drivers-windows#562] opened 2021-03-22 15:28 UTC
I'm using a Proxmox 6.3 (Debian 10.8 / kernel 5.4 / QEMU 5.2) host and Windows 10 LTSC guest. On the guest: Virtio-win x64 0.1.190 and WinFSP 1.9B2.  On the host: virtiofsd 7.32. 

When I try to rename files or folders I get the following:
![virtiofs](https://user-images.githubusercontent.com/10888060/112010806-04b18080-8afe-11eb-8b4b-0211d583e2e0.png)
See virtiofs.exe log [virtiofs0.log](https://github.com/virtio-win/kvm-guest-drivers-windows/files/6183172/virtiofs0.log).

Any way to get around this issue? Not sure if this is virtio-fs or WinFSP related. I've tried running the VM as UEFI and BIOS.

Running VM with the following argument for virtio-fs:
`-chardev socket,id=char0,path=/var/run/vm001-vhost-fs.sock -object memory-backend-memfd,id=mem,size=4G,share=on -numa node,memdev=mem -device vhost-user-fs-pci,chardev=char0,tag=myfs  `

virtiofsd is started with:
`./virtiofsd -d --socket-path=/var/run/vm001-vhost-fs.sock -o source=/mnt/tmp -o cache=always`

The filesystem on the host is ZFS with casesensitivity=insensitive and xattr=sa. chmod 777

I've found these somewhat similar issues, but none have resolved the rename issue:
[github.com/virtio-win/kvm-guest-drivers-windows/issues/550](https://github.com/virtio-win/kvm-guest-drivers-windows/issues/550)
[github.com/billziss-gh/winfsp/issues/196](https://github.com/billziss-gh/winfsp/issues/196)
[github.com/virtio-win/kvm-guest-drivers-windows/issues/473](https://github.com/virtio-win/kvm-guest-drivers-windows/issues/473)

**Comment by K0n24d** [comment] 2021-04-13 13:46
Exactly the same issue here but with slightly different setup:

Host Ubuntu 20.04 linux 5.8 with updated qemu 5.2 / libvirt 7.0.0
ZFS Filesystem with casesensitivity = sensitive
Guest Windows 10 with Virtio-win 1.9.0 / winfsp-1.8.20304

**Comment by xiagao** [comment] 2021-04-14 01:12
We have a similar issue in the downstream. 
The difference is the filesystem on the host is NFS with rw.
host pkg:
kernel-4.18.0-302.el8.x86_64
qemu-kvm-5.2.0-14.module+el8.4.0+10425+ad586fa5.x86_64

guest :
win2019
virtio-win-prewhql-0.1-197
winfsp-1.7.20172
So if there is any update, I will comment here.

**Comment by surfchris** [comment] 2021-04-14 18:10
> EDIT: this seems to be ZFS related. If I use a folder on an ext4 filesystem on the host It's working correctly.

That makes sense. I didn't have the chance to test with anything other than ZFS.

**Comment by surfchris** [comment] 2021-04-14 18:28
> We have a similar issue in the downstream.
> The difference is the filesystem on the host is NFS with rw.
> host pkg:
> kernel-4.18.0-302.el8.x86_64
> qemu-kvm-5.2.0-14.module+el8.4.0+10425+ad586fa5.x86_64
> 
> guest :
> win2019
> virtio-win-prewhql-0.1-197
> winfsp-1.7.20172
> So if there is any update, I will comment here.

**Comment by Dave--G** [comment] 2021-06-04 16:49
I experienced similar problems on Ubuntu 21.04 host with a Windows 10 guest but may have found a workaround.  At least it "works on my machine":
1. In the guest, disable starting virtiofs.exe as a service.
2. Create a batch file in `C:\Users\[your user name]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`
3. Enter the following in the batch file:
```
@echo on
start "vfio-fs" /min "C:\Program Files\Virtio-Win\VioFS\virtiofs.exe" -m z:
```
4. reboot.

I can't really explains why this works.  My guess is it's an windows execution context permission issue of some sort.  Supposedly fixed in new unpublished builds.

This is all on the v190 signed drivers since no newer builds are apparently available.

**Comment by Dave--G** [comment] 2021-06-07 05:26
Another finding for me is that these problems can be significantly reduced by adding the following to the vm's `<filesystem/>` xml configuration node:
`  <driver type="virtiofs" queue="1024"/>
  <binary path="/usr/lib/qemu/virtiofsd" xattr="on">
    <cache mode="always"/>
    <lock posix="on" flock="on"/>
  </binary>
`
However the remaining issues (discussed in other bugs here) remain.

**Comment by Ella-Fox** [comment] 2021-06-27 14:19
Mapping the virtiofs host directory to an exFAT based filesystem, I can reproduce this issue. The problem goes away when I'm using ext4.

**Comment by viktor-prutyanov** [comment] 2022-01-17 20:58
Hi @surfchris, @K0n24d, 

renaming files and folders seems to work on VirtIO-FS with ZFS as host filesystem.

Are you still experiencing problems?

**Comment by viktor-prutyanov** [comment] 2022-01-17 21:11
Hi @tinyfluffs,

renaming files and folders is also works on exFAT now. Is your problem gone?

**Comment by YanVugenfirer** [comment] 2022-01-31 12:29
Hello All,

Please help us understanding you use cases for using virtio-fs, and thus make us virtio-fs support better.
Please participate in the discussion and add your use cases: https://github.com/virtio-win/kvm-guest-drivers-windows/discussions/726

Thanks a lot,
Yan.

**Comment by viktor-prutyanov** [comment] 2022-04-23 20:25
Now renaming files and folders seems to work on ZFS and exFAT.

**Closed by viktor-prutyanov** 2022-04-23 20:25 UTC
Labels: Bug, virtio-fs
